# Generated by Django 4.2.8 on 2025-12-29 03:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='客户名称')),
                ('contact_person', models.CharField(blank=True, max_length=100, verbose_name='联系人')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='联系电话')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='邮箱')),
                ('address', models.TextField(blank=True, verbose_name='地址')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '客户',
                'verbose_name_plural': '客户管理',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='物料名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='物料编码')),
                ('specification', models.CharField(blank=True, max_length=200, verbose_name='规格')),
                ('unit', models.CharField(default='个', max_length=20, verbose_name='单位')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='单价')),
                ('stock_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='库存数量')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '物料',
                'verbose_name_plural': '物料管理',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='工序名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='工序编码')),
                ('description', models.TextField(blank=True, verbose_name='工序描述')),
                ('standard_duration', models.IntegerField(default=0, verbose_name='标准工时(小时)')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '工序',
                'verbose_name_plural': '工序管理',
                'ordering': ['sort_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=50, unique=True, verbose_name='施工单号')),
                ('product_name', models.CharField(max_length=200, verbose_name='产品名称')),
                ('specification', models.TextField(blank=True, verbose_name='产品规格')),
                ('quantity', models.IntegerField(default=1, verbose_name='数量')),
                ('unit', models.CharField(default='件', max_length=20, verbose_name='单位')),
                ('status', models.CharField(choices=[('pending', '待开始'), ('in_progress', '进行中'), ('paused', '已暂停'), ('completed', '已完成'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态')),
                ('priority', models.CharField(choices=[('low', '低'), ('normal', '普通'), ('high', '高'), ('urgent', '紧急')], default='normal', max_length=20, verbose_name='优先级')),
                ('order_date', models.DateField(default=django.utils.timezone.now, verbose_name='下单日期')),
                ('delivery_date', models.DateField(verbose_name='交货日期')),
                ('actual_delivery_date', models.DateField(blank=True, null=True, verbose_name='实际交货日期')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='总金额')),
                ('design_file', models.FileField(blank=True, null=True, upload_to='designs/', verbose_name='设计文件')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_orders', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workorder.customer', verbose_name='客户')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_orders', to=settings.AUTH_USER_MODEL, verbose_name='负责人')),
            ],
            options={
                'verbose_name': '施工单',
                'verbose_name_plural': '施工单管理',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkOrderProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.IntegerField(default=0, verbose_name='工序顺序')),
                ('status', models.CharField(choices=[('pending', '待开始'), ('in_progress', '进行中'), ('completed', '已完成'), ('skipped', '已跳过')], default='pending', max_length=20, verbose_name='状态')),
                ('planned_start_time', models.DateTimeField(blank=True, null=True, verbose_name='计划开始时间')),
                ('planned_end_time', models.DateTimeField(blank=True, null=True, verbose_name='计划结束时间')),
                ('actual_start_time', models.DateTimeField(blank=True, null=True, verbose_name='实际开始时间')),
                ('actual_end_time', models.DateTimeField(blank=True, null=True, verbose_name='实际结束时间')),
                ('duration_hours', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, verbose_name='耗时(小时)')),
                ('quantity_completed', models.IntegerField(default=0, verbose_name='完成数量')),
                ('quantity_defective', models.IntegerField(default=0, verbose_name='不良品数量')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operated_processes', to=settings.AUTH_USER_MODEL, verbose_name='操作员')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workorder.process', verbose_name='工序')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_processes', to='workorder.workorder', verbose_name='施工单')),
            ],
            options={
                'verbose_name': '施工单工序',
                'verbose_name_plural': '施工单工序管理',
                'ordering': ['work_order', 'sequence'],
                'unique_together': {('work_order', 'sequence')},
            },
        ),
        migrations.CreateModel(
            name='WorkOrderMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='计划用量')),
                ('actual_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='实际用量')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workorder.material', verbose_name='物料')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='workorder.workorder', verbose_name='施工单')),
            ],
            options={
                'verbose_name': '施工单物料',
                'verbose_name_plural': '施工单物料管理',
                'ordering': ['work_order', 'material'],
            },
        ),
        migrations.CreateModel(
            name='ProcessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(choices=[('start', '开始'), ('pause', '暂停'), ('resume', '恢复'), ('complete', '完成'), ('note', '备注')], max_length=20, verbose_name='日志类型')),
                ('content', models.TextField(verbose_name='内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作员')),
                ('work_order_process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='workorder.workorderprocess', verbose_name='工序')),
            ],
            options={
                'verbose_name': '工序日志',
                'verbose_name_plural': '工序日志',
                'ordering': ['-created_at'],
            },
        ),
    ]
