# Generated by Django 4.2.8 on 2025-12-29 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='产品名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='产品编码')),
                ('specification', models.CharField(blank=True, max_length=200, verbose_name='规格')),
                ('unit', models.CharField(default='件', max_length=20, verbose_name='单位')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='单价')),
                ('description', models.TextField(blank=True, verbose_name='产品描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '产品',
                'verbose_name_plural': '产品管理',
                'ordering': ['code'],
            },
        ),
        migrations.AlterField(
            model_name='workorder',
            name='order_number',
            field=models.CharField(editable=False, max_length=50, unique=True, verbose_name='施工单号'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='workorder.product', verbose_name='产品'),
        ),
    ]
