# Generated by Django 4.2.8 on 2026-01-07 00:35

from django.db import migrations

# 从共享数据源导入预设工序数据
# 注意：迁移文件可以导入应用代码，只要确保不导致循环依赖
try:
    from workorder.data import PRESET_PROCESSES, PRESET_PROCESS_CODES
except ImportError:
    # 如果导入失败（理论上不应该发生），使用内联数据作为后备
    PRESET_PROCESSES = [
        {'code': 'CTP', 'name': '制版', 'description': 'CTP制版', 'standard_duration': 0, 'sort_order': 1, 'is_active': True, 'is_builtin': True, 'task_generation_rule': 'general', 'is_parallel': True},
        {'code': 'CUT', 'name': '开料', 'description': '材料开料', 'standard_duration': 0, 'sort_order': 2, 'is_active': True, 'is_builtin': True, 'task_generation_rule': 'general', 'is_parallel': False},
        {'code': 'PRT', 'name': '印刷', 'description': '印刷', 'standard_duration': 0, 'sort_order': 3, 'is_active': True, 'is_builtin': True, 'task_generation_rule': 'general', 'is_parallel': False},
        {'code': 'VAN', 'name': '过油', 'description': '过油', 'standard_duration': 0, 'sort_order': 4, 'is_active': True, 'is_builtin': True, 'task_generation_rule': 'general', 'is_parallel': False},
        {'code': 'LAM_G', 'name': '覆光膜', 'description': '覆光膜', 'standard_duration': 0, 'sort_order': 5, 'is_active': True, 'is_builtin': True, 'task_generation_rule': 'general', 'is_parallel': False},
        {'code': 'LAM_M', 'name': '覆哑膜', 'description': '覆哑膜', 'standard_duration': 0, 'sort_order': 6, 'is_active': True, 'is_builtin': True, 'task_generation_rule': 'general', 'is_parallel': False},
        {'code': 'UV', 'name': 'UV', 'description': 'UV工艺', 'standard_duration': 0, 'sort_order': 7, 'is_active': True, 'is_builtin': True, 'task_generation_rule': 'general', 'is_parallel': False},
        {'code': 'FOIL_G', 'name': '烫金', 'description': '烫金', 'standard_duration': 0, 'sort_order': 8, 'is_active': True, 'is_builtin': True, 'task_generation_rule': 'general', 'is_parallel': False},
        {'code': 'FOIL_S', 'name': '烫银', 'description': '烫银', 'standard_duration': 0, 'sort_order': 9, 'is_active': True, 'is_builtin': True, 'task_generation_rule': 'general', 'is_parallel': False},
        {'code': 'EMB', 'name': '压凸', 'description': '压凸', 'standard_duration': 0, 'sort_order': 10, 'is_active': True, 'is_builtin': True, 'task_generation_rule': 'general', 'is_parallel': False},
        {'code': 'TEX', 'name': '压纹', 'description': '压纹', 'standard_duration': 0, 'sort_order': 11, 'is_active': True, 'is_builtin': True, 'task_generation_rule': 'general', 'is_parallel': False},
        {'code': 'SCORE', 'name': '压线', 'description': '压线', 'standard_duration': 0, 'sort_order': 12, 'is_active': True, 'is_builtin': True, 'task_generation_rule': 'general', 'is_parallel': False},
        {'code': 'DIE', 'name': '模切', 'description': '模切', 'standard_duration': 0, 'sort_order': 13, 'is_active': True, 'is_builtin': True, 'task_generation_rule': 'general', 'is_parallel': True},
        {'code': 'TRIM', 'name': '切成品', 'description': '切成品', 'standard_duration': 0, 'sort_order': 14, 'is_active': True, 'is_builtin': True, 'task_generation_rule': 'general', 'is_parallel': False},
        {'code': 'LAM_B', 'name': '对裱', 'description': '对裱', 'standard_duration': 0, 'sort_order': 15, 'is_active': True, 'is_builtin': True, 'task_generation_rule': 'general', 'is_parallel': False},
        {'code': 'MOUNT', 'name': '裱坑', 'description': '裱坑', 'standard_duration': 0, 'sort_order': 16, 'is_active': True, 'is_builtin': True, 'task_generation_rule': 'general', 'is_parallel': False},
        {'code': 'GLUE', 'name': '粘胶', 'description': '粘胶', 'standard_duration': 0, 'sort_order': 17, 'is_active': True, 'is_builtin': True, 'task_generation_rule': 'general', 'is_parallel': False},
        {'code': 'BOX', 'name': '粘盒', 'description': '粘盒', 'standard_duration': 0, 'sort_order': 18, 'is_active': True, 'is_builtin': True, 'task_generation_rule': 'general', 'is_parallel': False},
        {'code': 'WINDOW', 'name': '粘窗口', 'description': '粘窗口', 'standard_duration': 0, 'sort_order': 19, 'is_active': True, 'is_builtin': True, 'task_generation_rule': 'general', 'is_parallel': False},
        {'code': 'STAPLE', 'name': '打钉', 'description': '打钉', 'standard_duration': 0, 'sort_order': 20, 'is_active': True, 'is_builtin': True, 'task_generation_rule': 'general', 'is_parallel': False},
        {'code': 'PACK', 'name': '包装', 'description': '包装', 'standard_duration': 0, 'sort_order': 21, 'is_active': True, 'is_builtin': True, 'task_generation_rule': 'general', 'is_parallel': False},
    ]
    PRESET_PROCESS_CODES = [p['code'] for p in PRESET_PROCESSES]


def load_preset_processes_forward(apps, schema_editor):
    """加载预设的21个标准工序"""
    Process = apps.get_model('workorder', 'Process')
    
    # 检查是否已有数据，如果有则跳过
    if Process.objects.exists():
        return
    
    # 创建工序（使用共享数据源）
    for process_data in PRESET_PROCESSES:
        Process.objects.create(**process_data)


def load_preset_processes_backward(apps, schema_editor):
    """回滚迁移：删除预设工序"""
    Process = apps.get_model('workorder', 'Process')
    
    # 删除预设的21个工序（通过code匹配，使用共享数据源）
    Process.objects.filter(code__in=PRESET_PROCESS_CODES).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_preset_processes_forward, load_preset_processes_backward),
    ]
