# Generated by Django 4.2.8 on 2026-01-07 00:38

from django.db import migrations

# 从共享数据源导入预设部门数据
try:
    from workorder.data import (
        PRESET_MANAGEMENT_DEPARTMENTS,
        PRESET_PRODUCTION_DEPARTMENT,
        PRESET_WORKSHOP_DEPARTMENTS,
        PRESET_DEPARTMENT_CODES
    )
except ImportError:
    # 如果导入失败（理论上不应该发生），使用内联数据作为后备
    PRESET_MANAGEMENT_DEPARTMENTS = [
        {'name': '业务部', 'code': 'business', 'sort_order': 1, 'parent': None},
        {'name': '财务部', 'code': 'finance', 'sort_order': 2, 'parent': None},
        {'name': '设计部', 'code': 'design', 'sort_order': 3, 'parent': None},
        {'name': '采购部', 'code': 'purchase', 'sort_order': 4, 'parent': None},
        {'name': '运输部', 'code': 'logistics', 'sort_order': 11, 'parent': None},
    ]
    PRESET_PRODUCTION_DEPARTMENT = {
        'name': '生产部',
        'code': 'production',
        'sort_order': 5,
        'parent': None
    }
    PRESET_WORKSHOP_DEPARTMENTS = [
        {'name': '裁切车间', 'code': 'cutting', 'sort_order': 6},
        {'name': '印刷车间', 'code': 'printing', 'sort_order': 7},
        {'name': '外协车间', 'code': 'outsourcing', 'sort_order': 8},
        {'name': '模切车间', 'code': 'die_cutting', 'sort_order': 9},
        {'name': '包装车间', 'code': 'packaging', 'sort_order': 10},
    ]
    PRESET_DEPARTMENT_CODES = (
        [d['code'] for d in PRESET_MANAGEMENT_DEPARTMENTS] +
        [PRESET_PRODUCTION_DEPARTMENT['code']] +
        [d['code'] for d in PRESET_WORKSHOP_DEPARTMENTS]
    )


def load_departments_forward(apps, schema_editor):
    """加载预设部门数据，建立层级关系
    
    部门结构（共11个部门）：
    - 管理部门（5个，顶层）：业务部、财务部、设计部、采购部、运输部
    - 生产部（1个，父部门）
      - 裁切车间（子部门）
      - 印刷车间（子部门）
      - 外协车间（子部门）
      - 模切车间（子部门）
      - 包装车间（子部门）
    """
    Department = apps.get_model('workorder', 'Department')
    
    # 检查是否已有数据，如果有则跳过
    if Department.objects.exists():
        return
    
    # 1. 创建管理部门（顶层，使用共享数据源）
    for dept_data in PRESET_MANAGEMENT_DEPARTMENTS:
        Department.objects.create(
            name=dept_data['name'],
            code=dept_data['code'],
            sort_order=dept_data['sort_order'],
            is_active=True,
            parent=dept_data['parent']
        )
    
    # 2. 创建生产部（父部门，使用共享数据源）
    production_dept = Department.objects.create(
        name=PRESET_PRODUCTION_DEPARTMENT['name'],
        code=PRESET_PRODUCTION_DEPARTMENT['code'],
        sort_order=PRESET_PRODUCTION_DEPARTMENT['sort_order'],
        is_active=True,
        parent=PRESET_PRODUCTION_DEPARTMENT['parent']
    )
    
    # 3. 创建生产车间（子部门，使用共享数据源）
    for dept_data in PRESET_WORKSHOP_DEPARTMENTS:
        Department.objects.create(
            name=dept_data['name'],
            code=dept_data['code'],
            sort_order=dept_data['sort_order'],
            is_active=True,
            parent=production_dept
        )


def load_departments_backward(apps, schema_editor):
    """回滚迁移：删除预设部门"""
    Department = apps.get_model('workorder', 'Department')
    
    # 删除所有预设部门（使用共享数据源）
    Department.objects.filter(code__in=PRESET_DEPARTMENT_CODES).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0002_load_preset_processes'),
    ]

    operations = [
        migrations.RunPython(load_departments_forward, load_departments_backward),
    ]
