# Generated by Django 4.2.11 on 2026-06-07 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workorder", "0002_add_cut_fields_to_workordermaterial"),
    ]

    operations = [
        migrations.AddField(
            model_name="productstock",
            name="quality_status",
            field=models.CharField(
                choices=[
                    ("pending", "待检"),
                    ("qualified", "合格"),
                    ("concession", "让步接收"),
                    ("unqualified", "不合格"),
                ],
                default="pending",
                help_text="成品质检状态，只有合格/让步接收的批次才能发货",
                max_length=20,
                verbose_name="质检状态",
            ),
        ),
    ]
