# Generated by Django 4.2.8 on 2025-12-29 05:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workorder', '0002_product_alter_workorder_order_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='board_thickness',
            field=models.CharField(blank=True, help_text='如：3mm、5mm等', max_length=50, verbose_name='板材厚度'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='material_notes',
            field=models.TextField(blank=True, help_text='其他主材信息说明', verbose_name='主材备注'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='paper_brand',
            field=models.CharField(blank=True, help_text='如：金东、晨鸣等', max_length=100, verbose_name='纸张品牌'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='paper_type',
            field=models.CharField(blank=True, help_text='如：铜版纸、哑粉纸、白卡纸等', max_length=100, verbose_name='纸张类型'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='paper_weight',
            field=models.CharField(blank=True, help_text='如：157g、200g、250g等', max_length=50, verbose_name='纸张克数'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_orders', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_orders', to=settings.AUTH_USER_MODEL, verbose_name='制表人'),
        ),
    ]
