# Generated by Django 4.2.8 on 2025-12-29 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0003_workorder_board_thickness_workorder_material_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='board_thickness',
            field=models.CharField(blank=True, max_length=50, verbose_name='默认板材厚度'),
        ),
        migrations.AddField(
            model_name='product',
            name='paper_brand',
            field=models.CharField(blank=True, max_length=100, verbose_name='默认纸张品牌'),
        ),
        migrations.AddField(
            model_name='product',
            name='paper_type',
            field=models.CharField(blank=True, max_length=100, verbose_name='默认纸张类型'),
        ),
        migrations.AddField(
            model_name='product',
            name='paper_weight',
            field=models.CharField(blank=True, max_length=50, verbose_name='默认纸张克数'),
        ),
    ]
