# Generated by Django 4.2.8 on 2025-12-29 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0004_product_board_thickness_product_paper_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='post_processing',
            field=models.CharField(blank=True, max_length=200, verbose_name='默认后道工艺'),
        ),
        migrations.AddField(
            model_name='product',
            name='printing_method',
            field=models.CharField(blank=True, max_length=100, verbose_name='默认印刷方式/色数'),
        ),
        migrations.AddField(
            model_name='product',
            name='surface_treatment',
            field=models.CharField(blank=True, max_length=100, verbose_name='默认表面处理'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='post_processing',
            field=models.CharField(blank=True, help_text='如：烫金、烫银、模切、压痕、打孔等', max_length=200, verbose_name='后道工艺'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='printing_method',
            field=models.CharField(blank=True, help_text='如：单面四色、双面四色、单色印刷等', max_length=100, verbose_name='印刷方式/色数'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='process_notes',
            field=models.TextField(blank=True, help_text='其他工艺要求说明', verbose_name='工艺备注'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='surface_treatment',
            field=models.CharField(blank=True, help_text='如：UV、覆亮膜、覆哑膜、过油等', max_length=100, verbose_name='表面处理'),
        ),
    ]
