# Generated by Django 4.2.8 on 2026-01-07 00:59

from django.db import migrations
from django.contrib.auth.models import Group, Permission
from django.contrib.contenttypes.models import ContentType


def load_user_groups_forward(apps, schema_editor):
    """创建预设用户组并分配权限
    
    根据原管理命令 init_groups.py 的逻辑创建用户组
    """
    # 获取模型类
    WorkOrder = apps.get_model('workorder', 'WorkOrder')
    Customer = apps.get_model('workorder', 'Customer')
    Product = apps.get_model('workorder', 'Product')
    Material = apps.get_model('workorder', 'Material')
    Process = apps.get_model('workorder', 'Process')
    Department = apps.get_model('workorder', 'Department')
    Artwork = apps.get_model('workorder', 'Artwork')
    Die = apps.get_model('workorder', 'Die')
    ProductGroup = apps.get_model('workorder', 'ProductGroup')
    
    # 定义角色及其权限（与原 init_groups.py 保持一致）
    role_permissions = {
        '业务员': {
            'workorder': ['add', 'view', 'change'],  # 可以创建、查看、修改施工单
            'customer': ['add', 'view', 'change'],  # 可以创建、查看、修改客户
            'department': ['add', 'view', 'change'],  # 可以创建、查看、修改部门
            'process': ['add', 'view', 'change'],  # 可以创建、查看、修改工序
            'product': ['add', 'view', 'change'],  # 可以创建、查看、修改产品
            'material': ['add', 'view', 'change'],  # 可以创建、查看、修改物料
            'artwork': ['add', 'view', 'change'],  # 可以创建、查看、修改图稿
            'die': ['add', 'view', 'change'],  # 可以创建、查看、修改刀模
            'productgroup': ['add', 'view', 'change'],  # 可以创建、查看、修改产品组
        },
    }
    
    # 模型映射
    model_map = {
        'workorder': WorkOrder,
        'customer': Customer,
        'department': Department,
        'process': Process,
        'product': Product,
        'material': Material,
        'artwork': Artwork,
        'die': Die,
        'productgroup': ProductGroup,
    }
    
    # 创建组并分配权限
    for group_name, permissions_config in role_permissions.items():
        group, created = Group.objects.get_or_create(name=group_name)
        if created:
            print(f"✓ 成功创建用户组: {group_name}")
        else:
            print(f"⚠ 用户组已存在: {group_name}")
            # 如果组已存在，清除现有权限（确保权限一致性）
            group.permissions.clear()
        
        # 分配权限
        permissions_added = 0
        for model_name, actions in permissions_config.items():
            if model_name not in model_map:
                print(f"✗ 未知的模型: {model_name}")
                continue
            
            model = model_map[model_name]
            try:
                content_type = ContentType.objects.get_for_model(model)
            except ContentType.DoesNotExist:
                print(f"✗ ContentType 不存在: {model_name}")
                continue
            
            # 为每个操作添加权限
            for action in actions:
                codename = f'{action}_{model_name}'
                try:
                    permission = Permission.objects.get(
                        content_type=content_type,
                        codename=codename
                    )
                    if permission not in group.permissions.all():
                        group.permissions.add(permission)
                        permissions_added += 1
                except Permission.DoesNotExist:
                    print(f"✗ 权限不存在: {codename}")
        
        if permissions_added > 0:
            print(f"✓ 为 {group_name} 组添加了 {permissions_added} 个权限")
        else:
            print(f"⚠ {group_name} 组权限未变更")


def load_user_groups_backward(apps, schema_editor):
    """回滚操作：删除预设用户组"""
    Group = apps.get_model('auth', 'Group')
    
    # 删除预设的用户组
    preset_groups = ['业务员']
    Group.objects.filter(name__in=preset_groups).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0004_configure_department_processes'),
        # auth 和 contenttypes 应用在 Django 初始化时就已经存在，不需要显式声明依赖
    ]

    operations = [
        migrations.RunPython(load_user_groups_forward, load_user_groups_backward),
    ]
