# Generated by Django 4.2.8 on 2026-01-07 03:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workorder', '0005_load_user_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='workordertask',
            name='assigned_department',
            field=models.ForeignKey(blank=True, help_text='该任务分派给哪个部门执行', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to='workorder.department', verbose_name='分派部门'),
        ),
        migrations.AddField(
            model_name='workordertask',
            name='assigned_operator',
            field=models.ForeignKey(blank=True, help_text='该任务分派给哪个操作员执行', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL, verbose_name='分派操作员'),
        ),
    ]
