# Generated by Django 4.2.8 on 2025-12-29 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0005_product_post_processing_product_printing_method_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='post_processing',
        ),
        migrations.RemoveField(
            model_name='product',
            name='printing_method',
        ),
        migrations.RemoveField(
            model_name='product',
            name='surface_treatment',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='post_processing',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='printing_method',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='process_notes',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='surface_treatment',
        ),
        migrations.AddField(
            model_name='process',
            name='category',
            field=models.CharField(choices=[('prepress', '印前'), ('printing', '印刷'), ('surface', '表面处理'), ('postpress', '后道加工'), ('laminating', '复合/裱合'), ('forming', '成型/包装'), ('other', '其他')], default='other', max_length=20, verbose_name='工序类别'),
        ),
        migrations.AddField(
            model_name='product',
            name='default_processes',
            field=models.ManyToManyField(blank=True, help_text='创建施工单时将自动添加这些工序', to='workorder.process', verbose_name='默认工序'),
        ),
    ]
