# Generated by Django 4.2.11 on 2026-06-07 09:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workorder', '0005_add_actual_unit_price_to_workordermaterial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='已付金额'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', '未付款'), ('partial', '部分付款'), ('paid', '已付款')], default='unpaid', max_length=20, verbose_name='付款状态'),
        ),
        migrations.CreateModel(
            name='SupplierPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_number', models.CharField(editable=False, max_length=50, unique=True, verbose_name='付款单号')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='付款金额')),
                ('applied_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='核销金额')),
                ('remaining_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='剩余金额')),
                ('payment_method', models.CharField(choices=[('cash', '现金'), ('transfer', '转账'), ('check', '支票'), ('acceptance', '承兑汇票')], max_length=20, verbose_name='付款方式')),
                ('payment_date', models.DateField(default=django.utils.timezone.now, verbose_name='付款日期')),
                ('bank_account', models.CharField(blank=True, max_length=50, verbose_name='付款账户')),
                ('transaction_number', models.CharField(blank=True, max_length=100, verbose_name='交易流水号')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '已审核'), ('rejected', '已拒绝')], default='pending', max_length=20, verbose_name='审核状态')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='提交时间')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('approval_comment', models.TextField(blank=True, verbose_name='审核意见')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_supplier_payments', to=settings.AUTH_USER_MODEL, verbose_name='审核人')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_supplier_payments', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('purchase_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_payments', to='workorder.purchaseorder', verbose_name='采购单')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_supplier_payments', to=settings.AUTH_USER_MODEL, verbose_name='提交人')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='workorder.supplier', verbose_name='供应商')),
            ],
            options={
                'verbose_name': '供应商付款',
                'verbose_name_plural': '供应商付款管理',
                'ordering': ['-payment_date'],
                'indexes': [models.Index(fields=['supplier'], name='workorder_s_supplie_7111ed_idx'), models.Index(fields=['payment_date'], name='workorder_s_payment_3c479f_idx'), models.Index(fields=['status'], name='workorder_s_status_ccd6da_idx')],
            },
        ),
    ]
