# Generated by Django 4.2.11 on 2026-06-23 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workorder", "0007_material_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="default_tax_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=13,
                help_text="用于客户订单默认税率，如13表示13%",
                max_digits=5,
                verbose_name="默认税率",
            ),
        ),
    ]
