# Generated by Django 4.2.11 on 2026-06-25 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workorder", "0008_add_customer_default_tax_rate"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApprovalConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "singleton_key",
                    models.CharField(
                        default="default",
                        editable=False,
                        max_length=32,
                        unique=True,
                        verbose_name="单例键",
                    ),
                ),
                (
                    "workorder_approval_enabled",
                    models.BooleanField(default=True, verbose_name="施工单审核"),
                ),
                (
                    "salesorder_approval_enabled",
                    models.BooleanField(default=True, verbose_name="客户订单审核"),
                ),
                (
                    "purchaseorder_approval_enabled",
                    models.BooleanField(default=True, verbose_name="采购单审核"),
                ),
                (
                    "invoice_approval_enabled",
                    models.BooleanField(default=True, verbose_name="发票审核"),
                ),
                (
                    "supplierpayment_approval_enabled",
                    models.BooleanField(default=True, verbose_name="供应商付款审核"),
                ),
                (
                    "stockin_approval_enabled",
                    models.BooleanField(default=True, verbose_name="入库单审核"),
                ),
                (
                    "stockout_approval_enabled",
                    models.BooleanField(default=True, verbose_name="出库单审核"),
                ),
            ],
            options={
                "verbose_name": "审核开关设置",
                "verbose_name_plural": "审核开关设置",
            },
        ),
    ]
