# Generated by Django 4.2.8 on 2026-01-07 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0008_add_task_defective_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='workordertask',
            name='parent_task',
            field=models.ForeignKey(blank=True, help_text='如果该任务是子任务，指向父任务', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='workorder.workordertask', verbose_name='父任务'),
        ),
        migrations.AddField(
            model_name='workordertask',
            name='version',
            field=models.IntegerField(default=1, help_text='用于乐观锁，防止并发更新冲突', verbose_name='版本号'),
        ),
    ]
