# Generated by Django 4.2.8 on 2026-01-07 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0009_add_task_collaboration_support'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklog',
            name='quantity_defective_increment',
            field=models.IntegerField(blank=True, help_text='本次操作的不良品数量增量', null=True, verbose_name='不良品数量增量'),
        ),
    ]
