# Generated by Django 4.2.11 on 2026-07-17 01:51

from django.db import migrations, models
import workorder.upload_paths


class Migration(migrations.Migration):

    dependencies = [
        ("workorder", "0009_approvalconfig"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterField(
                    model_name="artworkimage",
                    name="image",
                    field=models.ImageField(
                        help_text="支持 JPG、PNG、WebP 等常见图片格式",
                        upload_to=workorder.upload_paths.artwork_image_upload_to,
                        verbose_name="图片文件",
                    ),
                ),
                migrations.AlterField(
                    model_name="deliveryorder",
                    name="receiver_signature",
                    field=models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=workorder.upload_paths.delivery_signature_upload_to,
                        verbose_name="签收照片",
                    ),
                ),
                migrations.AlterField(
                    model_name="dieimage",
                    name="image",
                    field=models.ImageField(
                        help_text="支持 JPG、PNG、WebP 等常见图片格式",
                        upload_to=workorder.upload_paths.die_image_upload_to,
                        verbose_name="图片文件",
                    ),
                ),
                migrations.AlterField(
                    model_name="embossingplateimage",
                    name="image",
                    field=models.ImageField(
                        help_text="支持 JPG、PNG、WebP 等常见图片格式",
                        upload_to=workorder.upload_paths.embossing_plate_image_upload_to,
                        verbose_name="图片文件",
                    ),
                ),
                migrations.AlterField(
                    model_name="foilingplateimage",
                    name="image",
                    field=models.ImageField(
                        help_text="支持 JPG、PNG、WebP 等常见图片格式",
                        upload_to=workorder.upload_paths.foiling_plate_image_upload_to,
                        verbose_name="图片文件",
                    ),
                ),
                migrations.AlterField(
                    model_name="invoice",
                    name="attachment",
                    field=models.FileField(
                        blank=True,
                        null=True,
                        upload_to=workorder.upload_paths.invoice_attachment_upload_to,
                        verbose_name="发票附件",
                    ),
                ),
                migrations.AlterField(
                    model_name="productimage",
                    name="image",
                    field=models.ImageField(
                        help_text="支持 JPG、PNG、WebP 等常见图片格式",
                        upload_to=workorder.upload_paths.product_image_upload_to,
                        verbose_name="图片文件",
                    ),
                ),
                migrations.AlterField(
                    model_name="qualityinspection",
                    name="attachment",
                    field=models.FileField(
                        blank=True,
                        null=True,
                        upload_to=workorder.upload_paths.quality_report_upload_to,
                        verbose_name="检验报告",
                    ),
                ),
                migrations.AlterField(
                    model_name="workorder",
                    name="design_file",
                    field=models.FileField(
                        blank=True,
                        null=True,
                        upload_to=workorder.upload_paths.work_order_design_upload_to,
                        verbose_name="设计文件",
                    ),
                ),
            ],
        ),
    ]
