# Generated by Django 4.2.8 on 2025-12-29 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0010_alter_process_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='material_size',
            field=models.CharField(blank=True, help_text='如：A4、210x297mm等', max_length=100, verbose_name='默认尺寸'),
        ),
        migrations.AddField(
            model_name='product',
            name='material_usage',
            field=models.CharField(blank=True, help_text='如：1000张、50平方米等', max_length=100, verbose_name='默认用量'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='material_size',
            field=models.CharField(blank=True, help_text='如：A4、210x297mm等', max_length=100, verbose_name='尺寸'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='material_usage',
            field=models.CharField(blank=True, help_text='如：1000张、50平方米等', max_length=100, verbose_name='用量'),
        ),
    ]
