# Generated by Django 4.2.8 on 2026-01-08 03:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0010_add_tasklog_defective_increment'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskAssignmentRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(default=0, help_text='优先级越高越优先匹配（0-100）', verbose_name='优先级')),
                ('operator_selection_strategy', models.CharField(choices=[('least_tasks', '任务数量最少（工作量均衡）'), ('random', '随机选择'), ('round_robin', '轮询分配'), ('first_available', '第一个可用')], default='least_tasks', help_text='从部门中选择操作员的策略', max_length=20, verbose_name='操作员选择策略')),
                ('is_active', models.BooleanField(default=True, help_text='是否启用该规则', verbose_name='是否启用')),
                ('notes', models.TextField(blank=True, help_text='规则说明或备注', verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('department', models.ForeignKey(help_text='该工序应分派到的部门', on_delete=django.db.models.deletion.CASCADE, related_name='assignment_rules', to='workorder.department', verbose_name='分派部门')),
                ('process', models.ForeignKey(help_text='该规则适用的工序', on_delete=django.db.models.deletion.CASCADE, related_name='assignment_rules', to='workorder.process', verbose_name='工序')),
            ],
            options={
                'verbose_name': '任务分派规则',
                'verbose_name_plural': '任务分派规则管理',
                'ordering': ['process', '-priority', 'department'],
                'unique_together': {('process', 'department')},
            },
        ),
    ]
