# Generated by Django 4.2.11 on 2026-07-18 02:27
# flake8: noqa: E501

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workorder', '0010_standardize_upload_paths'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='base_material',
            field=models.ForeignKey(blank=True, help_text='库存规格对应的上层材料要求，如大度150g双铜对应150g双铜', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_variants', to='workorder.material', verbose_name='对应材料要求'),
        ),
        migrations.AddField(
            model_name='material',
            name='grain_direction',
            field=models.CharField(blank=True, choices=[('', '未指定'), ('long', '长纹'), ('short', '短纹')], default='', max_length=10, verbose_name='纹向'),
        ),
        migrations.AddField(
            model_name='material',
            name='grammage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='克重(g/㎡)'),
        ),
        migrations.AddField(
            model_name='material',
            name='material_type',
            field=models.CharField(choices=[('paper', '纸张'), ('ink', '油墨'), ('film', '覆膜'), ('foil', '烫印料'), ('adhesive', '胶黏剂'), ('packing', '包装辅料'), ('other', '其他')], default='other', max_length=20, verbose_name='物料类型'),
        ),
        migrations.AddField(
            model_name='material',
            name='paper_type',
            field=models.CharField(blank=True, help_text='如双铜、双胶、白卡', max_length=100, verbose_name='纸张品种'),
        ),
        migrations.AddField(
            model_name='material',
            name='quality_hold_quantity',
            field=models.DecimalField(decimal_places=3, default=0, help_text='待检或质量冻结、不可用于生产的库存', max_digits=12, verbose_name='质量冻结数量'),
        ),
        migrations.AddField(
            model_name='material',
            name='reserved_quantity',
            field=models.DecimalField(decimal_places=3, default=0, help_text='已被施工单物料计划占用、尚未消耗的库存', max_digits=12, verbose_name='已预留数量'),
        ),
        migrations.AddField(
            model_name='material',
            name='sheet_height_mm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='纸张高度(mm)'),
        ),
        migrations.AddField(
            model_name='material',
            name='sheet_width_mm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='纸张宽度(mm)'),
        ),
        migrations.AddField(
            model_name='material',
            name='specification_level',
            field=models.CharField(choices=[('requirement', '材料要求'), ('stock', '库存/采购规格')], default='stock', help_text='材料要求用于产品BOM；库存/采购规格用于库存和采购', max_length=20, verbose_name='规格层级'),
        ),
        migrations.AddField(
            model_name='productmaterial',
            name='planning_required',
            field=models.BooleanField(default=False, help_text='产品阶段仅确定材料要求，拼版确认后再选择采购规格和计算数量', verbose_name='需拼版后规划'),
        ),
        migrations.AddField(
            model_name='workordermaterial',
            name='artwork',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_plans', to='workorder.artwork', verbose_name='拼版图稿'),
        ),
        migrations.AddField(
            model_name='workordermaterial',
            name='cut_height_mm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='开料高度(mm)'),
        ),
        migrations.AddField(
            model_name='workordermaterial',
            name='cut_width_mm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='开料宽度(mm)'),
        ),
        migrations.AddField(
            model_name='workordermaterial',
            name='inbound_quantity_snapshot',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='在途数量快照'),
        ),
        migrations.AddField(
            model_name='workordermaterial',
            name='parent_sheet_height_mm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='原纸高度(mm)'),
        ),
        migrations.AddField(
            model_name='workordermaterial',
            name='parent_sheet_width_mm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='原纸宽度(mm)'),
        ),
        migrations.AddField(
            model_name='workordermaterial',
            name='pieces_per_parent_sheet',
            field=models.PositiveIntegerField(default=0, verbose_name='每张原纸开出数'),
        ),
        migrations.AddField(
            model_name='workordermaterial',
            name='plan_confirmed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='规划确认时间'),
        ),
        migrations.AddField(
            model_name='workordermaterial',
            name='plan_confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_material_plans', to=settings.AUTH_USER_MODEL, verbose_name='规划确认人'),
        ),
        migrations.AddField(
            model_name='workordermaterial',
            name='plan_version',
            field=models.PositiveIntegerField(default=1, verbose_name='规划版本'),
        ),
        migrations.AddField(
            model_name='workordermaterial',
            name='planned_parent_quantity',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='计划原纸数量'),
        ),
        migrations.AddField(
            model_name='workordermaterial',
            name='planning_required',
            field=models.BooleanField(default=False, verbose_name='需拼版后规划'),
        ),
        migrations.AddField(
            model_name='workordermaterial',
            name='planning_status',
            field=models.CharField(choices=[('not_required', '无需规划'), ('draft', '待规划'), ('calculated', '已计算'), ('confirmed', '已确认'), ('invalidated', '已失效')], default='not_required', max_length=20, verbose_name='物料规划状态'),
        ),
        migrations.AddField(
            model_name='workordermaterial',
            name='purchase_material',
            field=models.ForeignKey(blank=True, help_text='拼版后选定的可库存、可采购具体规格', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='planned_work_order_materials', to='workorder.material', verbose_name='采购/库存规格'),
        ),
        migrations.AddField(
            model_name='workordermaterial',
            name='purchase_quantity',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='建议采购数量'),
        ),
        migrations.AddField(
            model_name='workordermaterial',
            name='required_cut_quantity',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='所需开料数量'),
        ),
        migrations.AddField(
            model_name='workordermaterial',
            name='reserved_quantity',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='已预留数量'),
        ),
        migrations.AddField(
            model_name='workordermaterial',
            name='theoretical_parent_quantity',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='理论原纸数量'),
        ),
        migrations.AddField(
            model_name='workordermaterial',
            name='wastage_rate',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6, verbose_name='计划损耗率(%)'),
        ),
    ]
