# Generated by Django 4.2.8 on 2026-01-08 03:30

from django.db import migrations
from workorder.data import PRESET_ASSIGNMENT_RULES


def load_preset_assignment_rules(apps, schema_editor):
    """加载预设的任务分派规则"""
    Process = apps.get_model('workorder', 'Process')
    Department = apps.get_model('workorder', 'Department')
    TaskAssignmentRule = apps.get_model('workorder', 'TaskAssignmentRule')
    
    # 创建规则映射（用于快速查找）
    process_map = {p.code: p for p in Process.objects.all()}
    department_map = {d.code: d for d in Department.objects.all()}
    
    # 加载预设规则
    created_count = 0
    skipped_count = 0
    
    for rule_data in PRESET_ASSIGNMENT_RULES:
        process_code = rule_data['process_code']
        department_code = rule_data['department_code']
        
        # 查找工序和部门
        process = process_map.get(process_code)
        department = department_map.get(department_code)
        
        if not process:
            print(f"警告: 工序编码 '{process_code}' 不存在，跳过规则")
            skipped_count += 1
            continue
        
        if not department:
            print(f"警告: 部门编码 '{department_code}' 不存在，跳过规则")
            skipped_count += 1
            continue
        
        # 检查是否已存在（避免重复创建）
        existing_rule = TaskAssignmentRule.objects.filter(
            process=process,
            department=department
        ).first()
        
        if existing_rule:
            # 更新现有规则
            existing_rule.priority = rule_data['priority']
            existing_rule.operator_selection_strategy = rule_data['operator_selection_strategy']
            existing_rule.is_active = True
            existing_rule.notes = rule_data.get('notes', '')
            existing_rule.save()
            print(f"更新规则: {process.name} -> {department.name} (优先级: {rule_data['priority']})")
        else:
            # 创建新规则
            TaskAssignmentRule.objects.create(
                process=process,
                department=department,
                priority=rule_data['priority'],
                operator_selection_strategy=rule_data['operator_selection_strategy'],
                is_active=True,
                notes=rule_data.get('notes', '')
            )
            created_count += 1
            print(f"创建规则: {process.name} -> {department.name} (优先级: {rule_data['priority']})")
    
    print(f"分派规则加载完成: 创建 {created_count} 条，更新 {TaskAssignmentRule.objects.count() - created_count} 条，跳过 {skipped_count} 条")


def reverse_load_preset_assignment_rules(apps, schema_editor):
    """回滚：删除所有预设的分派规则"""
    TaskAssignmentRule = apps.get_model('workorder', 'TaskAssignmentRule')
    Process = apps.get_model('workorder', 'Process')
    
    # 获取所有预设工序编码
    from workorder.data import PRESET_PROCESS_CODES
    
    # 删除所有与预设工序相关的规则
    preset_processes = Process.objects.filter(code__in=PRESET_PROCESS_CODES)
    deleted_count = TaskAssignmentRule.objects.filter(process__in=preset_processes).delete()[0]
    print(f"已删除 {deleted_count} 条预设分派规则")


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0011_add_task_assignment_rule'),
    ]

    operations = [
        migrations.RunPython(load_preset_assignment_rules, reverse_load_preset_assignment_rules),
    ]
