# Generated by Django 4.2.11 on 2026-07-18 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0011_material_planning'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmaterial',
            name='calculation_mode',
            field=models.CharField(choices=[('fixed', '固定/直接填写'), ('sheet_imposition', '拼版后算纸')], default='fixed', max_length=30, verbose_name='需求计算方式'),
        ),
        migrations.AddField(
            model_name='productmaterial',
            name='preparation_mode',
            field=models.CharField(choices=[('direct', '直接领用/采购'), ('internal_cutting', '厂内开料'), ('supplier_cutting', '供应商按尺寸供货')], default='direct', max_length=30, verbose_name='备料方式'),
        ),
        migrations.AddField(
            model_name='workordermaterial',
            name='calculation_mode',
            field=models.CharField(choices=[('fixed', '固定/直接填写'), ('sheet_imposition', '拼版后算纸')], default='fixed', max_length=30, verbose_name='需求计算方式'),
        ),
        migrations.AddField(
            model_name='workordermaterial',
            name='preparation_mode',
            field=models.CharField(choices=[('direct', '直接领用/采购'), ('internal_cutting', '厂内开料'), ('supplier_cutting', '供应商按尺寸供货')], default='direct', max_length=30, verbose_name='备料方式'),
        ),
    ]
