# Generated by Django 4.2.8 on 2025-12-29 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0012_workordermaterial_material_size_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_size', models.CharField(blank=True, help_text='如：A4、210x297mm等', max_length=100, verbose_name='尺寸')),
                ('material_usage', models.CharField(blank=True, help_text='如：1000张、50平方米等', max_length=100, verbose_name='用量')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workorder.material', verbose_name='物料')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='default_materials', to='workorder.product', verbose_name='产品')),
            ],
            options={
                'verbose_name': '产品默认物料',
                'verbose_name_plural': '产品默认物料管理',
                'ordering': ['product', 'sort_order'],
                'unique_together': {('product', 'material')},
            },
        ),
    ]
