# Generated by Django 4.2.11 on 2026-07-18 03:18

from django.db import migrations


def forward(apps, schema_editor):
    for model_name in ("ProductMaterial", "WorkOrderMaterial"):
        model = apps.get_model("workorder", model_name)
        model.objects.filter(planning_required=True).update(
            calculation_mode="sheet_imposition",
            preparation_mode="supplier_cutting",
        )
        model.objects.filter(need_cutting=True).update(
            preparation_mode="internal_cutting"
        )


def reverse(apps, schema_editor):
    for model_name in ("ProductMaterial", "WorkOrderMaterial"):
        model = apps.get_model("workorder", model_name)
        model.objects.update(planning_required=False, need_cutting=False)
        model.objects.filter(calculation_mode="sheet_imposition").update(
            planning_required=True
        )
        model.objects.filter(preparation_mode="internal_cutting").update(
            need_cutting=True
        )


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0012_productmaterial_calculation_mode_and_more'),
    ]

    operations = [migrations.RunPython(forward, reverse)]
