# Generated by Django 4.2.8 on 2026-01-08 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0012_load_preset_assignment_rules'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        # 为Die模型添加确认字段
        migrations.AddField(
            model_name='die',
            name='confirmed',
            field=models.BooleanField(default=False, help_text='设计部是否已确认该刀模', verbose_name='已确认'),
        ),
        migrations.AddField(
            model_name='die',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_dies', to='auth.user', verbose_name='确认人'),
        ),
        migrations.AddField(
            model_name='die',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='确认时间'),
        ),
        # 为FoilingPlate模型添加确认字段
        migrations.AddField(
            model_name='foilingplate',
            name='confirmed',
            field=models.BooleanField(default=False, help_text='设计部是否已确认该烫金版', verbose_name='已确认'),
        ),
        migrations.AddField(
            model_name='foilingplate',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_foiling_plates', to='auth.user', verbose_name='确认人'),
        ),
        migrations.AddField(
            model_name='foilingplate',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='确认时间'),
        ),
        # 为EmbossingPlate模型添加确认字段
        migrations.AddField(
            model_name='embossingplate',
            name='confirmed',
            field=models.BooleanField(default=False, help_text='设计部是否已确认该压凸版', verbose_name='已确认'),
        ),
        migrations.AddField(
            model_name='embossingplate',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_embossing_plates', to='auth.user', verbose_name='确认人'),
        ),
        migrations.AddField(
            model_name='embossingplate',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='确认时间'),
        ),
    ]
