# Generated by Django 4.2.8 on 2025-12-29 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0013_productmaterial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, editable=False, max_length=50, unique=True, verbose_name='图稿编码')),
                ('name', models.CharField(max_length=200, verbose_name='图稿名称')),
                ('color_count', models.IntegerField(default=4, help_text='如：1色、2色、4色等', verbose_name='色数')),
                ('imposition_size', models.CharField(blank=True, help_text='如：420x594mm、889x1194mm等', max_length=100, verbose_name='拼版尺寸')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '图稿',
                'verbose_name_plural': '图稿管理',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ArtworkProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imposition_quantity', models.IntegerField(default=1, help_text='该产品在图稿中的拼版数量', verbose_name='拼版数量')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('artwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='workorder.artwork', verbose_name='图稿')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workorder.product', verbose_name='产品')),
            ],
            options={
                'verbose_name': '图稿产品',
                'verbose_name_plural': '图稿产品管理',
                'ordering': ['artwork', 'sort_order'],
                'unique_together': {('artwork', 'product')},
            },
        ),
    ]
