# Generated by Django 4.2.8 on 2025-12-29 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0014_artwork_artworkproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='Die',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, editable=False, max_length=50, unique=True, verbose_name='刀模编码')),
                ('name', models.CharField(max_length=200, verbose_name='刀模名称')),
                ('size', models.CharField(blank=True, help_text='如：420x594mm、889x1194mm等', max_length=100, verbose_name='尺寸')),
                ('material', models.CharField(blank=True, help_text='如：木板、胶板等', max_length=100, verbose_name='材质')),
                ('thickness', models.CharField(blank=True, help_text='如：3mm、5mm等', max_length=50, verbose_name='厚度')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '刀模',
                'verbose_name_plural': '刀模管理',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DieProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, help_text='该产品在刀模中的数量', verbose_name='数量')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('die', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='workorder.die', verbose_name='刀模')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workorder.product', verbose_name='产品')),
            ],
            options={
                'verbose_name': '刀模产品',
                'verbose_name_plural': '刀模产品管理',
                'ordering': ['die', 'sort_order'],
                'unique_together': {('die', 'product')},
            },
        ),
    ]
