# Generated by Django 4.2 on 2026-01-10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0014_add_notification_system'),
    ]

    operations = [
        # 创建 Supplier 模型（先创建，因为 Material 需要引用它）
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='供应商名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='供应商编码')),
                ('contact_person', models.CharField(blank=True, max_length=100, verbose_name='联系人')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='联系电话')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='邮箱')),
                ('address', models.TextField(blank=True, verbose_name='地址')),
                ('status', models.CharField(choices=[('active', '启用'), ('inactive', '停用')], default='active', max_length=20, verbose_name='状态')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '供应商',
                'verbose_name_plural': '供应商管理',
                'ordering': ['code'],
            },
        ),

        # 扩展 Material 模型（在 Supplier 创建后）
        migrations.AddField(
            model_name='material',
            name='default_supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_materials', to='workorder.supplier', verbose_name='默认供应商', blank=True),
        ),
        migrations.AddField(
            model_name='material',
            name='lead_time_days',
            field=models.IntegerField(default=7, help_text='从下单到收货的天数', verbose_name='采购周期（天）'),
        ),
        migrations.AddField(
            model_name='material',
            name='min_stock_quantity',
            field=models.DecimalField(decimal_places=2, default=0, help_text='库存低于此数量时触发预警', max_digits=10, verbose_name='最小库存'),
        ),
        migrations.AddField(
            model_name='material',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),

        # 创建 PurchaseOrder 模型
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=50, unique=True, verbose_name='采购单号')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('submitted', '已提交'), ('approved', '已批准'), ('ordered', '已下单'), ('received', '已收货'), ('cancelled', '已取消')], default='draft', max_length=20, verbose_name='状态')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='总金额')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='提交时间')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('ordered_date', models.DateField(blank=True, help_text='向供应商下单的日期', null=True, verbose_name='下单日期')),
                ('expected_date', models.DateField(blank=True, help_text='供应商预计的到货日期', null=True, verbose_name='预计到货日期')),
                ('actual_received_date', models.DateField(blank=True, help_text='实际收货日期', null=True, verbose_name='实际到货日期')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('rejection_reason', models.TextField(blank=True, help_text='如果采购单被拒绝，填写拒绝原因', verbose_name='拒绝原因')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_purchase_orders', to='auth.user', verbose_name='审核人')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_purchase_orders', to='auth.user', verbose_name='提交人')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workorder.supplier', verbose_name='供应商')),
                ('work_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders', to='workorder.workorder', verbose_name='关联施工单')),
            ],
            options={
                'verbose_name': '采购单',
                'verbose_name_plural': '采购单管理',
                'ordering': ['-created_at'],
            },
        ),

        # 创建 PurchaseOrderItem 模型
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='采购数量')),
                ('received_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='已收货数量')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='单价')),
                ('supplier_code', models.CharField(blank=True, max_length=100, verbose_name='供应商物料编码')),
                ('status', models.CharField(choices=[('pending', '待收货'), ('partial', '部分收货'), ('received', '已收货')], default='pending', max_length=20, verbose_name='收货状态')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workorder.material', verbose_name='物料')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='workorder.purchaseorder', verbose_name='采购单')),
                ('work_order_material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workorder.workordermaterial', verbose_name='关联施工单物料')),
            ],
            options={
                'verbose_name': '采购单明细',
                'verbose_name_plural': '采购单明细管理',
                'ordering': ['purchase_order', 'id'],
            },
        ),

        # 创建 MaterialSupplier 模型（最后创建，因为需要引用 Material 和 Supplier）
        migrations.CreateModel(
            name='MaterialSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_code', models.CharField(blank=True, help_text='供应商提供的物料编码', max_length=100, verbose_name='供应商物料编码')),
                ('supplier_price', models.DecimalField(decimal_places=2, help_text='该供应商提供的单价', max_digits=10, verbose_name='供应商价格')),
                ('is_preferred', models.BooleanField(default=False, help_text='是否为该物料的首选供应商', verbose_name='首选供应商')),
                ('min_order_quantity', models.DecimalField(decimal_places=2, default=1, help_text='该供应商的最小起订量', max_digits=10, verbose_name='最小起订量')),
                ('lead_time_days', models.IntegerField(default=7, help_text='该供应商的采购周期', verbose_name='采购周期（天）')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_suppliers', to='workorder.material', verbose_name='物料')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_suppliers', to='workorder.supplier', verbose_name='供应商')),
            ],
            options={
                'verbose_name': '物料供应商关联',
                'verbose_name_plural': '物料供应商关联管理',
                'ordering': ['material', 'supplier'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='materialsupplier',
            unique_together={('material', 'supplier')},
        ),

        # 更新 Notification 模型
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('approval_passed', '审核通过'), ('approval_rejected', '审核拒绝'), ('reapproval_requested', '请求重新审核'), ('task_assigned', '任务分派'), ('task_due_soon', '任务即将到期'), ('process_completed', '工序完成'), ('workorder_completed', '施工单完成'), ('task_cancelled', '任务取消'), ('purchase_order_submitted', '采购单待审核'), ('purchase_order_approved', '采购单已批准'), ('purchase_order_rejected', '采购单已拒绝'), ('purchase_order_received', '采购单已收货'), ('low_stock_warning', '库存不足预警'), ('system', '系统通知')], max_length=30, verbose_name='通知类型'),
        ),
        migrations.AddField(
            model_name='notification',
            name='purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='workorder.purchaseorder', verbose_name='关联采购单'),
        ),
    ]
