# Generated by Django 4.2.8 on 2025-12-29 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0015_die_dieproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='die',
            name='code',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='刀模编码'),
        ),
    ]
