# Generated by Django 4.2.8 on 2026-01-10 05:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workorder', '0015_add_purchase_management'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=50, unique=True, verbose_name='销售订单号')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('submitted', '已提交'), ('approved', '已审核'), ('in_production', '生产中'), ('completed', '已完成'), ('cancelled', '已取消')], default='draft', max_length=20, verbose_name='订单状态')),
                ('payment_status', models.CharField(choices=[('unpaid', '未付款'), ('partial', '部分付款'), ('paid', '已付款')], default='unpaid', max_length=20, verbose_name='付款状态')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, help_text='订单明细总金额', max_digits=12, verbose_name='小计')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0, help_text='税率，如0.13表示13%', max_digits=5, verbose_name='税率')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='税额')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='折扣金额')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='订单总金额')),
                ('order_date', models.DateField(default=django.utils.timezone.now, verbose_name='订单日期')),
                ('delivery_date', models.DateField(verbose_name='预计交货日期')),
                ('actual_delivery_date', models.DateField(blank=True, null=True, verbose_name='实际交货日期')),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='定金')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='已付金额')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='付款日期')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='提交时间')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('approval_comment', models.TextField(blank=True, verbose_name='审核意见')),
                ('contact_person', models.CharField(blank=True, max_length=100, verbose_name='联系人')),
                ('contact_phone', models.CharField(blank=True, max_length=50, verbose_name='联系电话')),
                ('shipping_address', models.TextField(blank=True, verbose_name='送货地址')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('rejection_reason', models.TextField(blank=True, help_text='如果订单被拒绝，填写拒绝原因', verbose_name='拒绝原因')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '销售订单',
                'verbose_name_plural': '销售订单管理',
                'ordering': ['-created_at'],
                'permissions': [('change_approved_salesorder', '可以编辑已审核的销售订单')],
            },
        ),
        migrations.CreateModel(
            name='SalesOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='数量')),
                ('unit', models.CharField(default='件', max_length=20, verbose_name='单位')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='单价')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0, help_text='该明细的税率，默认使用订单税率', max_digits=5, verbose_name='税率')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='折扣金额')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='小计')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '销售订单明细',
                'verbose_name_plural': '销售订单明细管理',
                'ordering': ['sales_order', 'id'],
            },
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='workorder_n_recipie_e6212f_idx',
            old_name='workorder_n_recipie_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='workorder_n_notific_70fe26_idx',
            old_name='workorder_n_notific_idx',
        ),
        migrations.AlterField(
            model_name='material',
            name='default_supplier',
            field=models.ForeignKey(blank=True, help_text='该物料的默认供应商', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_materials', to='workorder.supplier', verbose_name='默认供应商'),
        ),
        migrations.AlterField(
            model_name='materialsupplier',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workorder.material', verbose_name='物料'),
        ),
        migrations.AlterField(
            model_name='materialsupplier',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workorder.supplier', verbose_name='供应商'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='actual_received_date',
            field=models.DateField(blank=True, null=True, verbose_name='实际到货日期'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='ordered_date',
            field=models.DateField(blank=True, null=True, verbose_name='下单日期'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='work_order',
            field=models.ForeignKey(blank=True, help_text='如果是为了某个施工单采购，可关联该施工单', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders', to='workorder.workorder', verbose_name='关联施工单'),
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='work_order_material',
            field=models.ForeignKey(blank=True, help_text='如果是为了某个施工单采购的物料，可关联', null=True, on_delete=django.db.models.deletion.SET_NULL, to='workorder.workordermaterial', verbose_name='关联施工单物料'),
        ),
        migrations.AddField(
            model_name='salesorderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workorder.product', verbose_name='产品'),
        ),
        migrations.AddField(
            model_name='salesorderitem',
            name='sales_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='workorder.salesorder', verbose_name='销售订单'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_sales_orders', to=settings.AUTH_USER_MODEL, verbose_name='审核人'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sales_orders', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workorder.customer', verbose_name='客户'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_sales_orders', to=settings.AUTH_USER_MODEL, verbose_name='提交人'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='work_orders',
            field=models.ManyToManyField(blank=True, to='workorder.workorder', verbose_name='关联施工单'),
        ),
    ]
