# Generated by Django 4.2.8 on 2025-12-29 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0016_alter_die_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='board_thickness',
        ),
        migrations.RemoveField(
            model_name='product',
            name='material_size',
        ),
        migrations.RemoveField(
            model_name='product',
            name='material_usage',
        ),
        migrations.RemoveField(
            model_name='product',
            name='paper_brand',
        ),
        migrations.RemoveField(
            model_name='product',
            name='paper_type',
        ),
        migrations.RemoveField(
            model_name='product',
            name='paper_weight',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='board_thickness',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='material_notes',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='material_size',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='material_usage',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='paper_brand',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='paper_type',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='paper_weight',
        ),
    ]
