# Generated by Django 4.2.8 on 2025-12-29 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0017_remove_product_board_thickness_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='artwork',
            field=models.ForeignKey(blank=True, help_text='关联的图稿，用于CTP制版', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders', to='workorder.artwork', verbose_name='图稿（CTP版）'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='die',
            field=models.ForeignKey(blank=True, help_text='关联的刀模，用于模切工序', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders', to='workorder.die', verbose_name='刀模'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='imposition_quantity',
            field=models.IntegerField(default=1, help_text='如：2拼、4拼等', verbose_name='拼版数量'),
        ),
    ]
