# Generated by Django 4.2.8 on 2026-01-10 08:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workorder', '0017_add_stock_quantity_to_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductStockLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.CharField(choices=[('add', '入库'), ('reduce', '出库')], max_length=20, verbose_name='变更类型')),
                ('quantity', models.IntegerField(help_text='正数表示入库，负数表示出库', verbose_name='变更数量')),
                ('old_quantity', models.IntegerField(verbose_name='变更前库存')),
                ('new_quantity', models.IntegerField(verbose_name='变更后库存')),
                ('reason', models.TextField(blank=True, verbose_name='变更原因')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_stock_logs', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_logs', to='workorder.product', verbose_name='产品')),
            ],
            options={
                'verbose_name': '产品库存日志',
                'verbose_name_plural': '产品库存日志管理',
                'ordering': ['-created_at'],
            },
        ),
    ]
