# Generated by Django 4.2 on 2026-01-20
# 添加产品表的性能优化索引

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0017_add_stock_quantity_to_product'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name'], name='product_name_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active'], name='product_is_active_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['stock_quantity'], name='product_stock_idx'),
        ),
    ]
