# Generated by Django 4.2.8 on 2025-12-29 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0018_workorder_artwork_workorder_die_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workordermaterial',
            name='cut_date',
            field=models.DateField(blank=True, help_text='切料组开料日期', null=True, verbose_name='开料日期'),
        ),
        migrations.AddField(
            model_name='workordermaterial',
            name='purchase_date',
            field=models.DateField(blank=True, help_text='采购下单日期', null=True, verbose_name='采购日期'),
        ),
        migrations.AddField(
            model_name='workordermaterial',
            name='purchase_status',
            field=models.CharField(choices=[('pending', '待采购'), ('ordered', '已下单'), ('received', '已回料'), ('cut', '已开料'), ('completed', '已完成')], default='pending', help_text='物料的采购和开料状态', max_length=20, verbose_name='采购状态'),
        ),
        migrations.AddField(
            model_name='workordermaterial',
            name='received_date',
            field=models.DateField(blank=True, help_text='物料回料日期', null=True, verbose_name='回料日期'),
        ),
    ]
