# Generated by Django 4.2.11 on 2026-07-30 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workorder", "0018_salesorder_status_approved"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliveryorder",
            name="subtotal",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=12, verbose_name="未税金额"
            ),
        ),
        migrations.AddField(
            model_name="deliveryorder",
            name="tax_amount",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=12, verbose_name="税额"
            ),
        ),
        migrations.AddField(
            model_name="deliveryorder",
            name="tax_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="整张送货单税率百分比，如13表示13%",
                max_digits=5,
                verbose_name="税率",
            ),
        ),
        migrations.AddField(
            model_name="deliveryorder",
            name="total_amount",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=12, verbose_name="价税合计"
            ),
        ),
        migrations.AlterField(
            model_name="salesorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "待处理"),
                    ("approved", "已审核"),
                    ("in_production", "生产中"),
                    ("ready_to_deliver", "待送货"),
                    ("partially_delivered", "部分送货"),
                    ("completed", "已完成"),
                    ("cancelled", "已取消"),
                ],
                default="pending",
                max_length=20,
                verbose_name="订单状态",
            ),
        ),
    ]
