# Generated by Django 4.2.8 on 2026-01-10 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0018_add_product_stock_management'),
    ]

    operations = [
        migrations.AddField(
            model_name='workordertask',
            name='stock_accounted_quantity',
            field=models.IntegerField(default=0, help_text='该任务已计入产品库存的完成数量，用于编辑数量时计算差异', verbose_name='已计入库存的完成数量'),
        ),
    ]
