# Generated by Django 4.2.11 on 2026-07-30 03:33

from django.db import migrations
from django.db.models import F, Sum


def backfill_simplified_sales_data(apps, schema_editor):
    SalesOrder = apps.get_model("workorder", "SalesOrder")
    SalesOrderItem = apps.get_model("workorder", "SalesOrderItem")
    WorkOrder = apps.get_model("workorder", "WorkOrder")
    DeliveryOrder = apps.get_model("workorder", "DeliveryOrder")
    DeliveryItem = apps.get_model("workorder", "DeliveryItem")

    SalesOrderItem.objects.update(
        tax_rate=0,
        discount_amount=0,
        subtotal=F("quantity") * F("unit_price"),
    )

    for sales_order in SalesOrder.objects.all().iterator(chunk_size=500):
        subtotal = (
            SalesOrderItem.objects.filter(sales_order_id=sales_order.id).aggregate(
                total=Sum("subtotal")
            )["total"]
            or 0
        )
        SalesOrder.objects.filter(pk=sales_order.pk).update(
            subtotal=subtotal,
            tax_rate=0,
            tax_amount=0,
            discount_amount=0,
            total_amount=subtotal,
        )
        if sales_order.status == "cancelled":
            continue

        items = list(
            SalesOrderItem.objects.filter(sales_order_id=sales_order.id).only(
                "quantity", "delivered_quantity"
            )
        )
        all_delivered = bool(items) and all(
            item.delivered_quantity >= item.quantity for item in items
        )
        has_delivery = any(item.delivered_quantity > 0 for item in items)
        work_orders = WorkOrder.objects.filter(sales_order_id=sales_order.id)

        if all_delivered:
            next_status = "completed"
        elif has_delivery:
            next_status = "partially_delivered"
        elif work_orders.filter(
            status__in=["pending", "in_progress", "paused"]
        ).exists():
            next_status = "in_production"
        elif work_orders.exists():
            next_status = "ready_to_deliver"
        else:
            next_status = "pending"

        if sales_order.status != next_status:
            SalesOrder.objects.filter(pk=sales_order.pk).update(status=next_status)

    for delivery_order in DeliveryOrder.objects.all().iterator(chunk_size=500):
        subtotal = sum(
            (
                item.subtotal
                for item in DeliveryItem.objects.filter(
                    delivery_order_id=delivery_order.id
                ).only("subtotal")
            ),
            0,
        )
        DeliveryOrder.objects.filter(pk=delivery_order.pk).update(
            subtotal=subtotal,
            tax_amount=0,
            total_amount=subtotal,
        )


def reverse_simplified_sales_data(apps, schema_editor):
    SalesOrder = apps.get_model("workorder", "SalesOrder")
    SalesOrder.objects.filter(status="ready_to_deliver").update(status="approved")
    SalesOrder.objects.filter(status="partially_delivered").update(
        status="in_production"
    )


class Migration(migrations.Migration):

    dependencies = [
        ("workorder", "0019_simplify_sales_and_add_delivery_tax"),
    ]

    operations = [
        migrations.RunPython(
            backfill_simplified_sales_data,
            reverse_simplified_sales_data,
        ),
    ]
