# Generated by Django 4.2.8 on 2026-01-14 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0019_add_stock_accounted_quantity_to_task'),
        ('workorder', 'add_indexes'),
    ]

    operations = [
    ]
