# Generated by Django 4.2.8 on 2026-01-15 11:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0019_add_stock_accounted_quantity_to_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='order_date',
            field=models.DateField(default=datetime.date.today, verbose_name='下单日期'),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['status'], name='workorder_w_status_270f39_idx'),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['priority'], name='workorder_w_priorit_60b9fe_idx'),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['approval_status'], name='workorder_w_approva_4ca378_idx'),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['customer'], name='workorder_w_custome_71c4bb_idx'),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['manager'], name='workorder_w_manager_9d07bf_idx'),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['created_by'], name='workorder_w_created_c12128_idx'),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['approved_by'], name='workorder_w_approve_918980_idx'),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['order_date'], name='workorder_w_order_d_a99258_idx'),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['delivery_date'], name='workorder_w_deliver_63cc88_idx'),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['status', 'priority'], name='workorder_w_status_a5f72c_idx'),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['customer', 'status'], name='workorder_w_custome_f8710e_idx'),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['approval_status', 'created_at'], name='workorder_w_approva_8620f0_idx'),
        ),
        migrations.AddIndex(
            model_name='workorderprocess',
            index=models.Index(fields=['status'], name='workorder_w_status_31f0b4_idx'),
        ),
        migrations.AddIndex(
            model_name='workorderprocess',
            index=models.Index(fields=['status', 'sequence'], name='workorder_w_status_c6d9a0_idx'),
        ),
        migrations.AddIndex(
            model_name='workorderprocess',
            index=models.Index(fields=['work_order', 'status'], name='workorder_w_work_or_4bd330_idx'),
        ),
        migrations.AddIndex(
            model_name='workorderprocess',
            index=models.Index(fields=['department'], name='workorder_w_departm_1cc03e_idx'),
        ),
        migrations.AddIndex(
            model_name='workorderprocess',
            index=models.Index(fields=['operator'], name='workorder_w_operato_c22286_idx'),
        ),
        migrations.AddIndex(
            model_name='workorderprocess',
            index=models.Index(fields=['planned_start_time'], name='workorder_w_planned_3e1bce_idx'),
        ),
        migrations.AddIndex(
            model_name='workorderprocess',
            index=models.Index(fields=['actual_start_time'], name='workorder_w_actual__517651_idx'),
        ),
        migrations.AddIndex(
            model_name='workordertask',
            index=models.Index(fields=['assigned_department'], name='workorder_w_assigne_a88d87_idx'),
        ),
        migrations.AddIndex(
            model_name='workordertask',
            index=models.Index(fields=['assigned_operator'], name='workorder_w_assigne_dcd513_idx'),
        ),
        migrations.AddIndex(
            model_name='workordertask',
            index=models.Index(fields=['status'], name='workorder_w_status_749097_idx'),
        ),
        migrations.AddIndex(
            model_name='workordertask',
            index=models.Index(fields=['assigned_department', 'status'], name='workorder_w_assigne_ce5900_idx'),
        ),
        migrations.AddIndex(
            model_name='workordertask',
            index=models.Index(fields=['work_order_process', 'status'], name='workorder_w_work_or_a4e784_idx'),
        ),
        migrations.AddIndex(
            model_name='workordertask',
            index=models.Index(fields=['task_type'], name='workorder_w_task_ty_ef4464_idx'),
        ),
        migrations.AddIndex(
            model_name='workordertask',
            index=models.Index(fields=['created_at'], name='workorder_w_created_563ab5_idx'),
        ),
        migrations.AddIndex(
            model_name='workordertask',
            index=models.Index(fields=['updated_at'], name='workorder_w_updated_d4f08f_idx'),
        ),
    ]
