# Generated by Django 4.2.8 on 2025-12-30 00:28

from django.db import migrations, models
import django.db.models.deletion


def migrate_processcategory_to_department(apps, schema_editor):
    """将 ProcessCategory 数据迁移到 Department，并创建预设部门"""
    ProcessCategory = apps.get_model('workorder', 'ProcessCategory')
    Department = apps.get_model('workorder', 'Department')
    Process = apps.get_model('workorder', 'Process')
    
    # 预设部门数据
    departments_data = [
        {'code': 'design', 'name': '设计', 'sort_order': 1},
        {'code': 'purchase', 'name': '采购', 'sort_order': 2},
        {'code': 'cutting', 'name': '开料', 'sort_order': 3},
        {'code': 'printing', 'name': '印刷', 'sort_order': 4},
        {'code': 'outsourcing', 'name': '外协', 'sort_order': 5},
        {'code': 'die_cutting', 'name': '模切', 'sort_order': 6},
        {'code': 'packaging', 'name': '包装', 'sort_order': 7},
    ]
    
    # 创建预设部门
    department_map = {}
    for dept_data in departments_data:
        dept, created = Department.objects.get_or_create(
            code=dept_data['code'],
            defaults={
                'name': dept_data['name'],
                'sort_order': dept_data['sort_order'],
                'is_active': True
            }
        )
        department_map[dept_data['code']] = dept
    
    # 迁移现有的 ProcessCategory 数据到 Department
    for category in ProcessCategory.objects.all():
        # 尝试根据 code 匹配预设部门
        dept = department_map.get(category.code)
        if not dept:
            # 如果没有匹配，创建新部门
            dept = Department.objects.create(
                code=category.code,
                name=category.name,
                sort_order=category.sort_order,
                is_active=category.is_active
            )
            department_map[category.code] = dept
        
        # 更新关联的 Process
        Process.objects.filter(category=category).update(department=dept)


def reverse_migrate(apps, schema_editor):
    """反向迁移：将 Department 数据迁移回 ProcessCategory"""
    ProcessCategory = apps.get_model('workorder', 'ProcessCategory')
    Department = apps.get_model('workorder', 'Department')
    Process = apps.get_model('workorder', 'Process')
    
    # 创建 ProcessCategory 并迁移数据
    for dept in Department.objects.all():
        category, _ = ProcessCategory.objects.get_or_create(
            code=dept.code,
            defaults={
                'name': dept.name,
                'sort_order': dept.sort_order,
                'is_active': dept.is_active
            }
        )
        # 更新关联的 Process
        Process.objects.filter(department=dept).update(category=category)


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0019_workordermaterial_cut_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='部门名称')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='部门编码')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '部门',
                'verbose_name_plural': '部门管理',
                'ordering': ['sort_order', 'code'],
            },
        ),
        migrations.AddField(
            model_name='process',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='processes', to='workorder.department', verbose_name='所属部门'),
        ),
        migrations.RunPython(migrate_processcategory_to_department, reverse_migrate),
        migrations.RemoveField(
            model_name='process',
            name='category',
        ),
        migrations.DeleteModel(
            name='ProcessCategory',
        ),
    ]
