# Generated by Django

from django.db import migrations, models, transaction
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0020_alter_workorder_order_date_and_more'),
    ]

    operations = [
        # 创建审核工作流表
        migrations.CreateModel(
            name='ApprovalWorkflow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True)),
                ('name', models.CharField(max_length=100)),
                ('workflow_type', models.CharField(max_length=20, choices=[
                    ('simple', '简单订单'),
                    ('standard', '标准订单'),
                    ('complex', '复杂订单'),
                    ('urgent', '紧急订单'),
                ])),
                ('description', models.TextField(blank=True)),
                ('steps', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('min_amount', models.DecimalField(max_digits=12, decimal_places=2, null=True, blank=True)),
                ('max_amount', models.DecimalField(max_digits=12, decimal_places=2, null=True, blank=True)),
                ('priority_filter', models.JSONField(default=list)),
                ('created_by', models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, related_name='created_workflows')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '审核工作流',
                'verbose_name_plural': '审核工作流管理',
                'ordering': ['-created_at'],
            },
        ),
        
        # 创建审核步骤表
        migrations.CreateModel(
            name='ApprovalStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True)),
                ('work_order', models.ForeignKey('workorder.WorkOrder', on_delete=models.CASCADE, related_name='approval_steps')),
                ('workflow', models.ForeignKey('ApprovalWorkflow', on_delete=models.SET_NULL, null=True, related_name='workflow_steps')),
                ('step_type', models.CharField(max_length=20, choices=[
                    ('review', '审核'),
                    ('approve', '批准'),
                    ('reject', '拒绝'),
                    ('escalate', '上报'),
                ])),
                ('step_name', models.CharField(max_length=100)),
                ('step_order', models.IntegerField(default=0)),
                ('assigned_to', models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, related_name='assigned_approval_steps')),
                ('role_filter', models.JSONField(default=list)),
                ('status', models.CharField(max_length=20, choices=[
                    ('pending', '待执行'),
                    ('in_progress', '执行中'),
                    ('completed', '已完成'),
                    ('skipped', '已跳过'),
                ], default='pending')),
                ('started_at', models.DateTimeField(null=True, blank=True)),
                ('completed_at', models.DateTimeField(null=True, blank=True)),
                ('decision', models.CharField(max_length=20, choices=[
                    ('approve', '批准'),
                    ('reject', '拒绝'),
                    ('escalate', '上报'),
                ], null=True, blank=True)),
                ('comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '审核步骤',
                'verbose_name_plural': '审核步骤管理',
                'ordering': ['work_order', 'step_order'],
                'unique_together': [('work_order', 'step_order')],
            },
        ),
        
        # 创建审核规则表
        migrations.CreateModel(
            name='ApprovalRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True)),
                ('workflow', models.ForeignKey('ApprovalWorkflow', on_delete=models.CASCADE, related_name='rules')),
                ('rule_type', models.CharField(max_length=20, choices=[
                    ('amount_threshold', '金额阈值'),
                    ('priority_match', '优先级匹配'),
                    ('customer_type', '客户类型'),
                    ('product_category', '产品类别'),
                    ('custom_rule', '自定义规则'),
                ])),
                ('rule_name', models.CharField(max_length=100)),
                ('conditions', models.JSONField(default=dict)),
                ('actions', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '审核规则',
                'verbose_name_plural': '审核规则管理',
                'ordering': ['-created_at'],
            },
        ),
        
        # 创建审核上报表
        migrations.CreateModel(
            name='ApprovalEscalation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True)),
                ('work_order', models.ForeignKey('workorder.WorkOrder', on_delete=models.CASCADE, related_name='escalations')),
                ('from_step', models.ForeignKey('ApprovalStep', on_delete=models.SET_NULL, null=True, related_name='escalations_from')),
                ('to_step', models.ForeignKey('ApprovalStep', on_delete=models.SET_NULL, null=True, related_name='escalations_to')),
                ('escalation_reason', models.TextField()),
                ('escalation_level', models.IntegerField(default=1)),
                ('status', models.CharField(max_length=20, choices=[
                    ('pending', '待处理'),
                    ('accepted', '已接受'),
                    ('rejected', '已拒绝'),
                    ('resolved', '已处理'),
                ], default='pending')),
                ('escalated_by', models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, related_name='escalations_made')),
                ('escalated_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_by', models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, related_name='escalations_resolved')),
                ('resolved_at', models.DateTimeField(null=True, blank=True)),
                ('resolution_comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '审核上报',
                'verbose_name_plural': '审核上报管理',
                'ordering': ['-created_at'],
            },
        ),
        
        # 为WorkOrder模型添加新字段
        migrations.AddField(
            model_name='workorder',
            name='multi_level_approval_enabled',
            field=models.BooleanField(
                default=False,
                verbose_name='是否启用多级审核',
                help_text='是否使用多级审核流程'
            ),
        ),
        
        migrations.AddField(
            model_name='workorder',
            name='current_workflow',
            field=models.ForeignKey(
                'workorder.ApprovalWorkflow',
                on_delete=models.SET_NULL,
                null=True,
                blank=True,
                related_name='current_workflow',
                verbose_name='当前审核工作流'
            ),
        ),
        
        migrations.AddField(
            model_name='workorder',
            name='urgency_reason',
            field=models.TextField(
                blank=True,
                verbose_name='紧急原因',
                help_text='标记为紧急订单的原因'
            ),
        ),
    ]