# Generated by Django 4.2.8 on 2025-12-30 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0020_rename_processcategory_to_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='process',
            name='department',
        ),
    ]
