# Generated by Django 4.2.11 on 2026-01-18 07:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workorder', '0021_add_multi_level_approval'),
    ]

    operations = [
        # ========== 财务模型 ==========

        # CostCenter
        migrations.CreateModel(
            name='CostCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='成本中心名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='成本中心编码')),
                ('type', models.CharField(choices=[('production', '生产部门'), ('auxiliary', '辅助部门'), ('management', '管理部门'), ('sales', '销售部门')], default='production', max_length=20, verbose_name='类型')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_cost_centers', to=settings.AUTH_USER_MODEL, verbose_name='负责人')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='workorder.costcenter', verbose_name='上级成本中心')),
            ],
            options={
                'verbose_name': '成本中心',
                'verbose_name_plural': '成本中心管理',
                'ordering': ['code'],
            },
        ),

        # CostItem
        migrations.CreateModel(
            name='CostItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='成本项目名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='成本项目编码')),
                ('type', models.CharField(choices=[('material', '直接材料'), ('labor', '直接人工'), ('equipment', '设备折旧'), ('overhead', '制造费用')], max_length=20, verbose_name='类型')),
                ('allocation_method', models.CharField(choices=[('direct', '直接分摊'), ('labor_hours', '按工时分摊'), ('machine_hours', '按机时分摊'), ('quantity', '按产量分摊'), ('value', '按产值分摊')], default='direct', max_length=20, verbose_name='分摊方法')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '成本项目',
                'verbose_name_plural': '成本项目管理',
                'ordering': ['code'],
            },
        ),

        # ProductionCost
        migrations.CreateModel(
            name='ProductionCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(help_text='格式: 2024-01', max_length=20, verbose_name='成本核算期')),
                ('material_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='材料成本')),
                ('labor_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='人工成本')),
                ('equipment_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='设备成本')),
                ('overhead_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='制造费用')),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='总成本')),
                ('standard_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='标准成本')),
                ('variance', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='成本差异')),
                ('variance_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='差异率')),
                ('calculated_at', models.DateTimeField(null=True, blank=True, verbose_name='核算时间')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('calculated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calculated_costs', to=settings.AUTH_USER_MODEL, verbose_name='核算人')),
                ('work_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='production_cost', to='workorder.workorder', verbose_name='施工单')),
            ],
            options={
                'verbose_name': '生产成本',
                'verbose_name_plural': '生产成本管理',
                'ordering': ['-period'],
            },
        ),

        # Invoice
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(editable=False, max_length=50, unique=True, verbose_name='发票号码')),
                ('invoice_code', models.CharField(blank=True, max_length=50, verbose_name='发票代码')),
                ('invoice_type', models.CharField(choices=[('vat_special', '增值税专用发票'), ('vat_normal', '增值税普通发票'), ('electronic', '电子发票')], default='vat_normal', max_length=20, verbose_name='发票类型')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='金额(不含税)')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=13, max_digits=5, verbose_name='税率')),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='税额')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='价税合计')),
                ('issue_date', models.DateField(blank=True, null=True, verbose_name='开票日期')),
                ('status', models.CharField(choices=[('draft', '待开具'), ('issued', '已开具'), ('sent', '已发送'), ('received', '已收到'), ('cancelled', '已作废'), ('refunded', '已红冲')], default='draft', max_length=20, verbose_name='状态')),
                ('customer_tax_number', models.CharField(blank=True, max_length=50, verbose_name='客户税号')),
                ('customer_address', models.TextField(blank=True, verbose_name='客户地址')),
                ('customer_phone', models.CharField(blank=True, max_length=50, verbose_name='客户电话')),
                ('customer_bank', models.CharField(blank=True, max_length=100, verbose_name='开户行')),
                ('customer_account', models.CharField(blank=True, max_length=50, verbose_name='账号')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='invoices/', verbose_name='发票附件')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='提交时间')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_invoices', to=settings.AUTH_USER_MODEL, verbose_name='审核人')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_invoices', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workorder.customer', verbose_name='客户')),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_invoices', to=settings.AUTH_USER_MODEL, verbose_name='提交人')),
                ('sales_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='workorder.salesorder', verbose_name='销售订单')),
                ('work_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='workorder.workorder', verbose_name='施工单')),
            ],
            options={
                'verbose_name': '发票',
                'verbose_name_plural': '发票管理',
                'ordering': ['-created_at'],
            },
        ),

        # Payment
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_number', models.CharField(editable=False, max_length=50, unique=True, verbose_name='收款单号')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='收款金额')),
                ('payment_method', models.CharField(choices=[('cash', '现金'), ('transfer', '转账'), ('check', '支票'), ('acceptance', '承兑汇票')], max_length=20, verbose_name='收款方式')),
                ('payment_date', models.DateField(verbose_name='收款日期')),
                ('bank_account', models.CharField(blank=True, max_length=50, verbose_name='收款账户')),
                ('transaction_number', models.CharField(blank=True, max_length=100, verbose_name='交易流水号')),
                ('applied_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='核销金额')),
                ('remaining_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='剩余金额')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workorder.customer', verbose_name='客户')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='workorder.invoice', verbose_name='关联发票')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_payments', to=settings.AUTH_USER_MODEL, verbose_name='记录人')),
                ('sales_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='workorder.salesorder', verbose_name='销售订单')),
            ],
            options={
                'verbose_name': '收款记录',
                'verbose_name_plural': '收款管理',
                'ordering': ['-payment_date'],
            },
        ),

        # PaymentPlan
        migrations.CreateModel(
            name='PaymentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='计划金额')),
                ('plan_date', models.DateField(verbose_name='计划收款日期')),
                ('status', models.CharField(choices=[('pending', '待收款'), ('partial', '部分收款'), ('completed', '已完成')], default='pending', max_length=20, verbose_name='状态')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='已收金额')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('sales_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_plans', to='workorder.salesorder', verbose_name='销售订单')),
            ],
            options={
                'verbose_name': '收款计划',
                'verbose_name_plural': '收款计划管理',
                'ordering': ['plan_date'],
            },
        ),

        # Statement
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement_number', models.CharField(editable=False, max_length=50, unique=True, verbose_name='对账单号')),
                ('statement_type', models.CharField(choices=[('customer', '客户对账单'), ('supplier', '供应商对账单')], default='customer', max_length=20, verbose_name='对账单类型')),
                ('period', models.CharField(help_text='格式: 2024-01', max_length=20, verbose_name='对账周期')),
                ('start_date', models.DateField(verbose_name='开始日期')),
                ('end_date', models.DateField(verbose_name='结束日期')),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='期初余额')),
                ('total_debit', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='本期借方')),
                ('total_credit', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='本期贷方')),
                ('closing_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='期末余额')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('sent', '已发送'), ('confirmed', '已确认'), ('disputed', '有异议')], default='draft', max_length=20, verbose_name='状态')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='确认时间')),
                ('confirmation_notes', models.TextField(blank=True, verbose_name='确认备注')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('confirmed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_statements', to=settings.AUTH_USER_MODEL, verbose_name='确认人')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_statements', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='statements', to='workorder.customer', verbose_name='客户')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='statements', to='workorder.supplier', verbose_name='供应商')),
            ],
            options={
                'verbose_name': '对账单',
                'verbose_name_plural': '对账单管理',
                'ordering': ['-period'],
            },
        ),

        # ========== 库存模型 ==========

        # ProductStock
        migrations.CreateModel(
            name='ProductStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='库存数量')),
                ('location', models.CharField(blank=True, help_text='如: A01-01-01', max_length=50, verbose_name='库位')),
                ('batch_no', models.CharField(max_length=50, unique=True, verbose_name='批次号')),
                ('production_date', models.DateField(blank=True, null=True, verbose_name='生产日期')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='有效期')),
                ('status', models.CharField(choices=[('in_stock', '在库'), ('reserved', '已预留'), ('quality_check', '质检中'), ('defective', '次品')], default='in_stock', max_length=20, verbose_name='状态')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workorder.product', verbose_name='产品')),
                ('work_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_stocks', to='workorder.workorder', verbose_name='来源施工单')),
            ],
            options={
                'verbose_name': '成品库存',
                'verbose_name_plural': '成品库存管理',
                'ordering': ['-created_at'],
            },
        ),

        # StockIn
        migrations.CreateModel(
            name='StockIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(editable=False, max_length=50, unique=True, verbose_name='入库单号')),
                ('stock_in_date', models.DateField(verbose_name='入库日期')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('submitted', '已提交'), ('approved', '已审核'), ('completed', '已完成'), ('cancelled', '已取消')], default='draft', max_length=20, verbose_name='状态')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='提交时间')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_stock_ins', to=settings.AUTH_USER_MODEL, verbose_name='审核人')),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operated_stock_ins', to=settings.AUTH_USER_MODEL, verbose_name='操作员')),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_stock_ins', to=settings.AUTH_USER_MODEL, verbose_name='提交人')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_ins', to='workorder.workorder', verbose_name='施工单')),
            ],
            options={
                'verbose_name': '入库单',
                'verbose_name_plural': '入库单管理',
                'ordering': ['-created_at'],
            },
        ),

        # DeliveryOrder (必须在StockOut之前创建)
        migrations.CreateModel(
            name='DeliveryOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(editable=False, max_length=50, unique=True, verbose_name='发货单号')),
                ('delivery_date', models.DateField(blank=True, null=True, verbose_name='发货日期')),
                ('status', models.CharField(choices=[('pending', '待发货'), ('shipped', '已发货'), ('in_transit', '运输中'), ('received', '已签收'), ('rejected', '拒收'), ('returned', '已退货')], default='pending', max_length=20, verbose_name='状态')),
                ('receiver_name', models.CharField(max_length=100, verbose_name='收货人')),
                ('receiver_phone', models.CharField(max_length=50, verbose_name='联系电话')),
                ('delivery_address', models.TextField(verbose_name='送货地址')),
                ('logistics_company', models.CharField(blank=True, max_length=100, verbose_name='物流公司')),
                ('tracking_number', models.CharField(blank=True, max_length=100, verbose_name='物流单号')),
                ('freight', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='运费')),
                ('received_date', models.DateTimeField(blank=True, null=True, verbose_name='签收时间')),
                ('receiver_signature', models.ImageField(blank=True, null=True, upload_to='signatures/', verbose_name='签收照片')),
                ('received_notes', models.TextField(blank=True, verbose_name='签收备注')),
                ('package_count', models.IntegerField(default=1, verbose_name='包裹数量')),
                ('package_weight', models.DecimalField(blank=True, null=True, decimal_places=2, max_digits=10, verbose_name='总重量(kg)')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_delivery_orders', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workorder.customer', verbose_name='客户')),
                ('sales_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_orders', to='workorder.salesorder', verbose_name='销售订单')),
            ],
            options={
                'verbose_name': '发货单',
                'verbose_name_plural': '发货单管理',
                'ordering': ['-created_at'],
            },
        ),

        # DeliveryItem
        migrations.CreateModel(
            name='DeliveryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='发货数量')),
                ('unit', models.CharField(default='件', max_length=20, verbose_name='单位')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='单价')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='小计')),
                ('stock_batch', models.CharField(blank=True, max_length=50, verbose_name='库存批次号')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('delivery_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='workorder.deliveryorder', verbose_name='发货单')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workorder.product', verbose_name='产品')),
            ],
            options={
                'verbose_name': '发货明细',
                'verbose_name_plural': '发货明细管理',
                'ordering': ['delivery_order', 'id'],
            },
        ),

        # StockOut (在DeliveryOrder之后)
        migrations.CreateModel(
            name='StockOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(editable=False, max_length=50, unique=True, verbose_name='出库单号')),
                ('out_type', models.CharField(choices=[('delivery', '发货出库'), ('return', '退货出库'), ('transfer', '调拨出库'), ('defective', '次品出库')], default='delivery', max_length=20, verbose_name='出库类型')),
                ('stock_out_date', models.DateField(verbose_name='出库日期')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('submitted', '已提交'), ('approved', '已审核'), ('completed', '已完成'), ('cancelled', '已取消')], default='draft', max_length=20, verbose_name='状态')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='提交时间')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_stock_outs', to=settings.AUTH_USER_MODEL, verbose_name='审核人')),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operated_stock_outs', to=settings.AUTH_USER_MODEL, verbose_name='操作员')),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_stock_outs', to=settings.AUTH_USER_MODEL, verbose_name='提交人')),
                ('delivery_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_outs', to='workorder.deliveryorder', verbose_name='发货单')),
            ],
            options={
                'verbose_name': '出库单',
                'verbose_name_plural': '出库单管理',
                'ordering': ['-created_at'],
            },
        ),

        # QualityInspection
        migrations.CreateModel(
            name='QualityInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_number', models.CharField(editable=False, max_length=50, unique=True, verbose_name='质检单号')),
                ('inspection_type', models.CharField(choices=[('incoming', '来料检验'), ('process', '过程检验'), ('final', '成品检验'), ('customer', '客诉检验')], max_length=20, verbose_name='检验类型')),
                ('batch_no', models.CharField(blank=True, max_length=50, verbose_name='批次号')),
                ('inspection_date', models.DateField(verbose_name='检验日期')),
                ('result', models.CharField(choices=[('pending', '待检验'), ('passed', '合格'), ('failed', '不合格'), ('conditional', '条件接收')], default='pending', max_length=20, verbose_name='检验结果')),
                ('inspection_quantity', models.IntegerField(default=0, verbose_name='检验数量')),
                ('passed_quantity', models.IntegerField(default=0, verbose_name='合格数量')),
                ('failed_quantity', models.IntegerField(default=0, verbose_name='不合格数量')),
                ('defective_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='不良率')),
                ('inspection_standard', models.TextField(blank=True, verbose_name='检验标准')),
                ('inspection_items', models.JSONField(blank=True, default=list, verbose_name='检验项目')),
                ('defects', models.JSONField(blank=True, default=list, verbose_name='缺陷记录')),
                ('defect_description', models.TextField(blank=True, verbose_name='缺陷描述')),
                ('disposition', models.CharField(blank=True, choices=[('accept', '接收'), ('rework', '返工'), ('scrap', '报废'), ('return', '退货')], max_length=20, verbose_name='处理意见')),
                ('disposition_notes', models.TextField(blank=True, verbose_name='处理说明')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='quality_reports/', verbose_name='检验报告')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('inspector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspections', to=settings.AUTH_USER_MODEL, verbose_name='质检员')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quality_inspections', to='workorder.product', verbose_name='产品')),
                ('work_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quality_inspections', to='workorder.workorder', verbose_name='施工单')),
            ],
            options={
                'verbose_name': '质量检验',
                'verbose_name_plural': '质量检验管理',
                'ordering': ['-inspection_date'],
            },
        ),
    ]
