# Generated by Django 4.2.8 on 2025-12-30 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0021_remove_process_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorderprocess',
            name='department',
            field=models.ForeignKey(blank=True, help_text='指定该工序由哪个部门生产', null=True, on_delete=django.db.models.deletion.PROTECT, to='workorder.department', verbose_name='生产部门'),
        ),
        migrations.CreateModel(
            name='WorkOrderTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_content', models.TextField(help_text='具体的施工内容描述', verbose_name='施工内容')),
                ('production_quantity', models.IntegerField(default=0, help_text='该任务需要生产的数量', verbose_name='生产数量')),
                ('production_requirements', models.TextField(blank=True, help_text='生产过程中的特殊要求', verbose_name='生产要求')),
                ('status', models.CharField(choices=[('pending', '待开始'), ('in_progress', '进行中'), ('completed', '已完成'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('work_order_process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='workorder.workorderprocess', verbose_name='工序')),
            ],
            options={
                'verbose_name': '施工单任务',
                'verbose_name_plural': '施工单任务管理',
                'ordering': ['work_order_process', 'created_at'],
            },
        ),
    ]
