# Generated by Django 4.2.11 on 2026-01-20 06:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("workorder", "0022_add_finance_and_inventory_models"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="approvalescalation",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "审核上报",
                "verbose_name_plural": "审核上报",
            },
        ),
        migrations.AlterModelOptions(
            name="approvalrule",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "审核规则",
                "verbose_name_plural": "审核规则",
            },
        ),
        migrations.AlterModelOptions(
            name="approvalstep",
            options={
                "ordering": ["work_order", "step_order"],
                "verbose_name": "审核步骤",
                "verbose_name_plural": "审核步骤",
            },
        ),
        migrations.AlterModelOptions(
            name="approvalworkflow",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "审核工作流",
                "verbose_name_plural": "审核工作流",
            },
        ),
        migrations.RemoveField(
            model_name="approvalescalation",
            name="escalated_at",
        ),
        migrations.RemoveField(
            model_name="approvalescalation",
            name="escalation_level",
        ),
        migrations.RemoveField(
            model_name="approvalrule",
            name="actions",
        ),
        migrations.RemoveField(
            model_name="approvalrule",
            name="rule_name",
        ),
        migrations.RemoveField(
            model_name="approvalrule",
            name="workflow",
        ),
        migrations.RemoveField(
            model_name="approvalstep",
            name="role_filter",
        ),
        migrations.RemoveField(
            model_name="approvalstep",
            name="step_type",
        ),
        migrations.RemoveField(
            model_name="approvalworkflow",
            name="max_amount",
        ),
        migrations.RemoveField(
            model_name="approvalworkflow",
            name="min_amount",
        ),
        migrations.RemoveField(
            model_name="approvalworkflow",
            name="priority_filter",
        ),
        migrations.AddField(
            model_name="approvalrule",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="创建人",
            ),
        ),
        migrations.AddField(
            model_name="approvalrule",
            name="name",
            field=models.CharField(
                default="默认规则", max_length=100, verbose_name="规则名称"
            ),
        ),
        migrations.AddField(
            model_name="approvalrule",
            name="workflow_type",
            field=models.CharField(
                choices=[
                    ("simple", "简单审核"),
                    ("standard", "标准审核"),
                    ("complex", "复杂审核"),
                    ("urgent", "紧急审核"),
                ],
                default="standard",
                max_length=20,
                verbose_name="工作流类型",
            ),
        ),
        migrations.AlterField(
            model_name="approvalescalation",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="approvalescalation",
            name="escalated_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="escalated_approvals",
                to=settings.AUTH_USER_MODEL,
                verbose_name="上报人",
            ),
        ),
        migrations.AlterField(
            model_name="approvalescalation",
            name="escalation_reason",
            field=models.TextField(verbose_name="上报原因"),
        ),
        migrations.AlterField(
            model_name="approvalescalation",
            name="from_step",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="escalations_from",
                to="workorder.approvalstep",
                verbose_name="原步骤",
            ),
        ),
        migrations.AlterField(
            model_name="approvalescalation",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="approvalescalation",
            name="resolution_comments",
            field=models.TextField(blank=True, verbose_name="处理意见"),
        ),
        migrations.AlterField(
            model_name="approvalescalation",
            name="resolved_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="处理时间"),
        ),
        migrations.AlterField(
            model_name="approvalescalation",
            name="resolved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="resolved_approvals",
                to=settings.AUTH_USER_MODEL,
                verbose_name="处理人",
            ),
        ),
        migrations.AlterField(
            model_name="approvalescalation",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "待处理"),
                    ("approved", "已批准"),
                    ("rejected", "已拒绝"),
                ],
                default="pending",
                max_length=20,
                verbose_name="状态",
            ),
        ),
        migrations.AlterField(
            model_name="approvalescalation",
            name="to_step",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="escalations_to",
                to="workorder.approvalstep",
                verbose_name="目标步骤",
            ),
        ),
        migrations.AlterField(
            model_name="approvalescalation",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
        migrations.AlterField(
            model_name="approvalescalation",
            name="work_order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="approval_escalations",
                to="workorder.workorder",
                verbose_name="施工单",
            ),
        ),
        migrations.AlterField(
            model_name="approvalrule",
            name="conditions",
            field=models.JSONField(default=dict, verbose_name="触发条件"),
        ),
        migrations.AlterField(
            model_name="approvalrule",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="approvalrule",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="approvalrule",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="是否激活"),
        ),
        migrations.AlterField(
            model_name="approvalrule",
            name="rule_type",
            field=models.CharField(
                choices=[
                    ("value_based", "基于价值"),
                    ("time_based", "基于时间"),
                    ("customer_based", "基于客户"),
                    ("product_based", "基于产品"),
                    ("department_based", "基于部门"),
                ],
                default="value_based",
                max_length=20,
                verbose_name="规则类型",
            ),
        ),
        migrations.AlterField(
            model_name="approvalrule",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
        migrations.AlterField(
            model_name="approvalstep",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_approval_steps",
                to=settings.AUTH_USER_MODEL,
                verbose_name="分配给",
            ),
        ),
        migrations.AlterField(
            model_name="approvalstep",
            name="comments",
            field=models.TextField(blank=True, verbose_name="审核意见"),
        ),
        migrations.AlterField(
            model_name="approvalstep",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="完成时间"),
        ),
        migrations.AlterField(
            model_name="approvalstep",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="approvalstep",
            name="decision",
            field=models.CharField(
                blank=True,
                choices=[("approve", "通过"), ("reject", "拒绝"), ("escalate", "上报")],
                max_length=20,
                verbose_name="审核决定",
            ),
        ),
        migrations.AlterField(
            model_name="approvalstep",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="approvalstep",
            name="started_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="开始时间"),
        ),
        migrations.AlterField(
            model_name="approvalstep",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "待审核"),
                    ("in_progress", "审核中"),
                    ("completed", "已完成"),
                    ("skipped", "已跳过"),
                ],
                default="pending",
                max_length=20,
                verbose_name="状态",
            ),
        ),
        migrations.AlterField(
            model_name="approvalstep",
            name="step_name",
            field=models.CharField(max_length=100, verbose_name="步骤名称"),
        ),
        migrations.AlterField(
            model_name="approvalstep",
            name="step_order",
            field=models.IntegerField(verbose_name="步骤顺序"),
        ),
        migrations.AlterField(
            model_name="approvalstep",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
        migrations.AlterField(
            model_name="approvalstep",
            name="work_order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="approval_steps",
                to="workorder.workorder",
                verbose_name="施工单",
            ),
        ),
        migrations.AlterField(
            model_name="approvalstep",
            name="workflow",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="workorder.approvalworkflow",
                verbose_name="工作流",
            ),
        ),
        migrations.AlterField(
            model_name="approvalworkflow",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="approvalworkflow",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="创建人",
            ),
        ),
        migrations.AlterField(
            model_name="approvalworkflow",
            name="description",
            field=models.TextField(blank=True, verbose_name="描述"),
        ),
        migrations.AlterField(
            model_name="approvalworkflow",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="approvalworkflow",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="是否激活"),
        ),
        migrations.AlterField(
            model_name="approvalworkflow",
            name="name",
            field=models.CharField(max_length=100, verbose_name="工作流名称"),
        ),
        migrations.AlterField(
            model_name="approvalworkflow",
            name="steps",
            field=models.JSONField(default=dict, verbose_name="审核步骤配置"),
        ),
        migrations.AlterField(
            model_name="approvalworkflow",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
        migrations.AlterField(
            model_name="approvalworkflow",
            name="workflow_type",
            field=models.CharField(
                choices=[
                    ("simple", "简单审核"),
                    ("standard", "标准审核"),
                    ("complex", "复杂审核"),
                    ("urgent", "紧急审核"),
                ],
                max_length=20,
                verbose_name="工作流类型",
            ),
        ),
        migrations.AlterField(
            model_name="costcenter",
            name="manager",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="managed_cost_centers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="负责人",
            ),
        ),
        migrations.AlterField(
            model_name="costcenter",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="workorder.costcenter",
                verbose_name="上级成本中心",
            ),
        ),
        migrations.AlterField(
            model_name="deliveryorder",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_delivery_orders",
                to=settings.AUTH_USER_MODEL,
                verbose_name="创建人",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_invoices",
                to=settings.AUTH_USER_MODEL,
                verbose_name="审核人",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_invoices",
                to=settings.AUTH_USER_MODEL,
                verbose_name="创建人",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="submitted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="submitted_invoices",
                to=settings.AUTH_USER_MODEL,
                verbose_name="提交人",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_date",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="收款日期"
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="recorded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="recorded_payments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="记录人",
            ),
        ),
        migrations.AlterField(
            model_name="productioncost",
            name="calculated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="calculated_costs",
                to=settings.AUTH_USER_MODEL,
                verbose_name="核算人",
            ),
        ),
        migrations.AlterField(
            model_name="qualityinspection",
            name="inspection_date",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="检验日期"
            ),
        ),
        migrations.AlterField(
            model_name="statement",
            name="confirmed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="confirmed_statements",
                to=settings.AUTH_USER_MODEL,
                verbose_name="确认人",
            ),
        ),
        migrations.AlterField(
            model_name="statement",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_statements",
                to=settings.AUTH_USER_MODEL,
                verbose_name="创建人",
            ),
        ),
        migrations.AlterField(
            model_name="statement",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="statements",
                to="workorder.customer",
                verbose_name="客户",
            ),
        ),
        migrations.AlterField(
            model_name="stockin",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_stock_ins",
                to=settings.AUTH_USER_MODEL,
                verbose_name="审核人",
            ),
        ),
        migrations.AlterField(
            model_name="stockin",
            name="operator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="operated_stock_ins",
                to=settings.AUTH_USER_MODEL,
                verbose_name="操作员",
            ),
        ),
        migrations.AlterField(
            model_name="stockin",
            name="stock_in_date",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="入库日期"
            ),
        ),
        migrations.AlterField(
            model_name="stockin",
            name="submitted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="submitted_stock_ins",
                to=settings.AUTH_USER_MODEL,
                verbose_name="提交人",
            ),
        ),
        migrations.AlterField(
            model_name="stockout",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_stock_outs",
                to=settings.AUTH_USER_MODEL,
                verbose_name="审核人",
            ),
        ),
        migrations.AlterField(
            model_name="stockout",
            name="operator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="operated_stock_outs",
                to=settings.AUTH_USER_MODEL,
                verbose_name="操作员",
            ),
        ),
        migrations.AlterField(
            model_name="stockout",
            name="stock_out_date",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="出库日期"
            ),
        ),
        migrations.AlterField(
            model_name="stockout",
            name="submitted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="submitted_stock_outs",
                to=settings.AUTH_USER_MODEL,
                verbose_name="提交人",
            ),
        ),
        migrations.AddIndex(
            model_name="deliveryorder",
            index=models.Index(fields=["status"], name="workorder_d_status_01be44_idx"),
        ),
        migrations.AddIndex(
            model_name="deliveryorder",
            index=models.Index(
                fields=["customer"], name="workorder_d_custome_ab509f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="deliveryorder",
            index=models.Index(
                fields=["delivery_date"], name="workorder_d_deliver_1712ca_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(fields=["status"], name="workorder_i_status_92e30d_idx"),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["customer"], name="workorder_i_custome_1f1781_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["issue_date"], name="workorder_i_issue_d_32e1d5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["customer"], name="workorder_p_custome_d189ad_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["payment_date"], name="workorder_p_payment_9ebc82_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productioncost",
            index=models.Index(fields=["period"], name="workorder_p_period_c55d7a_idx"),
        ),
        migrations.AddIndex(
            model_name="productioncost",
            index=models.Index(
                fields=["work_order"], name="workorder_p_work_or_562ea4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productstock",
            index=models.Index(
                fields=["product"], name="workorder_p_product_694520_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productstock",
            index=models.Index(
                fields=["batch_no"], name="workorder_p_batch_n_108015_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productstock",
            index=models.Index(fields=["status"], name="workorder_p_status_409829_idx"),
        ),
        migrations.AddIndex(
            model_name="productstock",
            index=models.Index(
                fields=["location"], name="workorder_p_locatio_66faf7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="qualityinspection",
            index=models.Index(
                fields=["inspection_type"], name="workorder_q_inspect_594d7a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="qualityinspection",
            index=models.Index(fields=["result"], name="workorder_q_result_5865fa_idx"),
        ),
        migrations.AddIndex(
            model_name="qualityinspection",
            index=models.Index(
                fields=["inspection_date"], name="workorder_q_inspect_1abfab_idx"
            ),
        ),
        migrations.AlterModelTable(
            name="approvalescalation",
            table="approval_escalation",
        ),
        migrations.AlterModelTable(
            name="approvalrule",
            table="approval_rule",
        ),
        migrations.AlterModelTable(
            name="approvalstep",
            table="approval_step",
        ),
        migrations.AlterModelTable(
            name="approvalworkflow",
            table="approval_workflow",
        ),
    ]
