# Generated by Django 4.2.8 on 2025-12-30 02:15

from django.db import migrations


def reset_departments(apps, schema_editor):
    """清空部门表并插入预设部门
    
    注意：
    - 此迁移创建部门时，parent字段可能还不存在（0066迁移会添加该字段）
    - 部门层级关系将在 0067_update_department_hierarchy 迁移中建立
    - 部门与工序的关联关系将在 0024_reset_processes 迁移中建立
    """
    Department = apps.get_model('workorder', 'Department')
    
    # 清空所有现有部门
    Department.objects.all().delete()
    
    # 预设部门数据（先创建为扁平结构，层级关系在0067中建立）
    departments = [
        {'name': '业务部', 'code': 'business', 'sort_order': 1},
        {'name': '财务部', 'code': 'finance', 'sort_order': 2},
        {'name': '设计部', 'code': 'design', 'sort_order': 3},
        {'name': '采购部', 'code': 'purchase', 'sort_order': 4},
        {'name': '生产部', 'code': 'production', 'sort_order': 5},
        {'name': '裁切车间', 'code': 'cutting', 'sort_order': 6},
        {'name': '印刷车间', 'code': 'printing', 'sort_order': 7},
        {'name': '外协车间', 'code': 'outsourcing', 'sort_order': 8},
        {'name': '模切车间', 'code': 'die_cutting', 'sort_order': 9},
        {'name': '包装车间', 'code': 'packaging', 'sort_order': 10},
        {'name': '运输部', 'code': 'logistics', 'sort_order': 11},
    ]
    
    # 插入预设部门（不使用parent字段，因为可能还不存在）
    for dept_data in departments:
        # 检查是否有parent字段
        dept_kwargs = {
            'name': dept_data['name'],
            'code': dept_data['code'],
            'sort_order': dept_data['sort_order'],
            'is_active': True,
        }
        # 如果parent字段存在，设置为None
        if hasattr(Department, 'parent'):
            dept_kwargs['parent'] = None
        Department.objects.create(**dept_kwargs)


def reverse_reset_departments(apps, schema_editor):
    """回滚操作：不恢复原有数据"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0022_workorderprocess_department_workordertask'),
        # 注意：如果0066_add_department_parent迁移已存在，应该依赖它
        # 但由于迁移编号顺序，0023在0066之前，所以这里不添加依赖
        # 实际执行时，Django会按编号顺序执行，0066会在0023之后执行
    ]

    operations = [
        migrations.RunPython(reset_departments, reverse_reset_departments),
    ]
