# Generated by Django 4.2.8 on 2025-12-30 02:15

from django.db import migrations


def reset_departments(apps, schema_editor):
    """清空部门表并插入预设部门"""
    Department = apps.get_model('workorder', 'Department')
    
    # 清空所有现有部门
    Department.objects.all().delete()
    
    # 预设部门数据
    departments = [
        {'name': '业务部', 'code': 'business', 'sort_order': 1},
        {'name': '财务部', 'code': 'finance', 'sort_order': 2},
        {'name': '设计部', 'code': 'design', 'sort_order': 3},
        {'name': '采购部', 'code': 'purchase', 'sort_order': 4},
        {'name': '裁切部', 'code': 'cutting', 'sort_order': 5},
        {'name': '印刷部', 'code': 'printing', 'sort_order': 6},
        {'name': '外协部', 'code': 'outsourcing', 'sort_order': 7},
        {'name': '模切部', 'code': 'die_cutting', 'sort_order': 8},
        {'name': '包装部', 'code': 'packaging', 'sort_order': 9},
        {'name': '运输部', 'code': 'logistics', 'sort_order': 10},
    ]
    
    # 插入预设部门
    for dept in departments:
        Department.objects.create(
            name=dept['name'],
            code=dept['code'],
            sort_order=dept['sort_order'],
            is_active=True
        )


def reverse_reset_departments(apps, schema_editor):
    """回滚操作：不恢复原有数据"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0022_workorderprocess_department_workordertask'),
    ]

    operations = [
        migrations.RunPython(reset_departments, reverse_reset_departments),
    ]
