# Generated by Django 4.2.8 on 2025-12-30 02:20

from django.db import migrations


def reset_processes(apps, schema_editor):
    """清空工序表并插入预设工序"""
    Process = apps.get_model('workorder', 'Process')
    
    # 清空所有现有工序
    Process.objects.all().delete()
    
    # 预设工序数据
    processes = [
        {'name': '制版', 'code': 'CTP', 'sort_order': 1, 'description': 'CTP制版'},
        {'name': '开料', 'code': 'CUT', 'sort_order': 2, 'description': '材料开料'},
        {'name': '印刷', 'code': 'PRT', 'sort_order': 3, 'description': '印刷'},
        {'name': '过油', 'code': 'VAN', 'sort_order': 4, 'description': '过油'},
        {'name': '覆光膜', 'code': 'LAM_G', 'sort_order': 5, 'description': '覆光膜'},
        {'name': '覆哑膜', 'code': 'LAM_M', 'sort_order': 6, 'description': '覆哑膜'},
        {'name': 'UV', 'code': 'UV', 'sort_order': 7, 'description': 'UV工艺'},
        {'name': '烫金', 'code': 'FOIL_G', 'sort_order': 8, 'description': '烫金'},
        {'name': '烫银', 'code': 'FOIL_S', 'sort_order': 9, 'description': '烫银'},
        {'name': '压凸', 'code': 'EMB', 'sort_order': 10, 'description': '压凸'},
        {'name': '压纹', 'code': 'TEX', 'sort_order': 11, 'description': '压纹'},
        {'name': '压线', 'code': 'SCORE', 'sort_order': 12, 'description': '压线'},
        {'name': '模切', 'code': 'DIE', 'sort_order': 13, 'description': '模切'},
        {'name': '切成品', 'code': 'TRIM', 'sort_order': 14, 'description': '切成品'},
        {'name': '对裱', 'code': 'LAM_B', 'sort_order': 15, 'description': '对裱'},
        {'name': '裱坑', 'code': 'MOUNT', 'sort_order': 16, 'description': '裱坑'},
        {'name': '粘胶', 'code': 'GLUE', 'sort_order': 17, 'description': '粘胶'},
        {'name': '粘盒', 'code': 'BOX', 'sort_order': 18, 'description': '粘盒'},
        {'name': '粘窗口', 'code': 'WINDOW', 'sort_order': 19, 'description': '粘窗口'},
        {'name': '打钉', 'code': 'STAPLE', 'sort_order': 20, 'description': '打钉'},
        {'name': '包装', 'code': 'PACK', 'sort_order': 21, 'description': '包装'},
    ]
    
    # 插入预设工序
    for proc in processes:
        Process.objects.create(
            name=proc['name'],
            code=proc['code'],
            description=proc.get('description', ''),
            standard_duration=0,
            sort_order=proc['sort_order'],
            is_active=True
        )


def reverse_reset_processes(apps, schema_editor):
    """回滚操作：不恢复原有数据"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0023_reset_departments'),
    ]

    operations = [
        migrations.RunPython(reset_processes, reverse_reset_processes),
    ]
