# Generated by Django 4.2.11 on 2026-01-20 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workorder", "0018_add_product_indexes"),
        ("workorder", "0023_alter_approvalescalation_options_and_more"),
    ]

    operations = []
