# Generated by Django 4.2.11 on 2026-01-20 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("workorder", "0024_merge_20260120_1819"),
    ]

    operations = [
        migrations.AlterField(
            model_name="material",
            name="default_supplier",
            field=models.ForeignKey(
                blank=True,
                help_text="该物料的默认供应商（保护模式，防止误删供应商）",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="default_materials",
                to="workorder.supplier",
                verbose_name="默认供应商",
            ),
        ),
        migrations.AlterField(
            model_name="material",
            name="min_stock_quantity",
            field=models.DecimalField(
                decimal_places=3,
                default=0,
                help_text="库存低于此数量时触发预警",
                max_digits=12,
                verbose_name="最小库存",
            ),
        ),
        migrations.AlterField(
            model_name="material",
            name="stock_quantity",
            field=models.DecimalField(
                decimal_places=3,
                default=0,
                help_text="当前库存数量",
                max_digits=12,
                verbose_name="库存数量",
            ),
        ),
        migrations.AlterField(
            model_name="material",
            name="unit_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="物料单价，最大值: 999999999.99",
                max_digits=12,
                verbose_name="单价",
            ),
        ),
        migrations.AddIndex(
            model_name="material",
            index=models.Index(fields=["name"], name="material_name_idx"),
        ),
        migrations.AddIndex(
            model_name="material",
            index=models.Index(fields=["code"], name="material_code_idx"),
        ),
        migrations.AddIndex(
            model_name="material",
            index=models.Index(fields=["stock_quantity"], name="material_stock_idx"),
        ),
        migrations.AddIndex(
            model_name="material",
            index=models.Index(
                fields=["default_supplier"], name="material_supplier_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="materialsupplier",
            index=models.Index(fields=["material"], name="ms_material_idx"),
        ),
        migrations.AddIndex(
            model_name="materialsupplier",
            index=models.Index(fields=["supplier"], name="ms_supplier_idx"),
        ),
        migrations.AddIndex(
            model_name="materialsupplier",
            index=models.Index(fields=["is_preferred"], name="ms_preferred_idx"),
        ),
        migrations.AddIndex(
            model_name="purchaseorder",
            index=models.Index(fields=["order_number"], name="po_number_idx"),
        ),
        migrations.AddIndex(
            model_name="purchaseorder",
            index=models.Index(fields=["status"], name="po_status_idx"),
        ),
        migrations.AddIndex(
            model_name="purchaseorder",
            index=models.Index(fields=["supplier"], name="po_supplier_idx"),
        ),
        migrations.AddIndex(
            model_name="purchaseorder",
            index=models.Index(fields=["created_at"], name="po_created_idx"),
        ),
        migrations.AddIndex(
            model_name="supplier",
            index=models.Index(fields=["name"], name="supplier_name_idx"),
        ),
        migrations.AddIndex(
            model_name="supplier",
            index=models.Index(fields=["code"], name="supplier_code_idx"),
        ),
        migrations.AddIndex(
            model_name="supplier",
            index=models.Index(fields=["status"], name="supplier_status_idx"),
        ),
    ]
