# Generated by Django 4.2.8 on 2025-12-30 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0024_reset_processes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='产品组名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='产品组编码')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '产品组',
                'verbose_name_plural': '产品组管理',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='WorkOrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='数量')),
                ('unit', models.CharField(default='件', max_length=20, verbose_name='单位')),
                ('specification', models.TextField(blank=True, verbose_name='产品规格')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workorder.product', verbose_name='产品')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='workorder.workorder', verbose_name='施工单')),
            ],
            options={
                'verbose_name': '施工单产品',
                'verbose_name_plural': '施工单产品管理',
                'ordering': ['work_order', 'sort_order'],
                'unique_together': {('work_order', 'product', 'sort_order')},
            },
        ),
        migrations.CreateModel(
            name='ProductGroupItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(help_text='如：天盒、地盒', max_length=200, verbose_name='子产品名称')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workorder.product', verbose_name='产品')),
                ('product_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='workorder.productgroup', verbose_name='产品组')),
            ],
            options={
                'verbose_name': '产品组子项',
                'verbose_name_plural': '产品组子项管理',
                'ordering': ['product_group', 'sort_order'],
                'unique_together': {('product_group', 'product')},
            },
        ),
    ]
