# Generated by Django 4.2.11 on 2026-01-20 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0025_add_material_indexes_and_optimize_fields'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='process',
            index=models.Index(fields=['name'], name='process_name_idx'),
        ),
        migrations.AddIndex(
            model_name='process',
            index=models.Index(fields=['code'], name='process_code_idx'),
        ),
        migrations.AddIndex(
            model_name='process',
            index=models.Index(fields=['is_active'], name='process_is_active_idx'),
        ),
        migrations.AddIndex(
            model_name='process',
            index=models.Index(fields=['sort_order'], name='process_sort_order_idx'),
        ),
        migrations.AddIndex(
            model_name='process',
            index=models.Index(fields=['is_active', 'sort_order'], name='process_active_sort_idx'),
        ),
    ]
