# Generated by Django 4.2.8 on 2025-12-30 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0025_add_product_group_and_workorder_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='product_group_item',
            field=models.ForeignKey(blank=True, help_text='如果该施工单是产品组的一部分，关联到对应的子产品', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders', to='workorder.productgroupitem', verbose_name='产品组子项'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='product',
            field=models.ForeignKey(blank=True, help_text='单个产品（兼容旧数据，建议使用 products 关联）', null=True, on_delete=django.db.models.deletion.PROTECT, to='workorder.product', verbose_name='产品'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='product_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='产品名称'),
        ),
    ]
