# Generated by Django 4.2.8 on 2025-12-30 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0026_add_product_group_item_to_workorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workorder',
            name='artwork',
        ),
        migrations.AddField(
            model_name='workorder',
            name='artworks',
            field=models.ManyToManyField(blank=True, help_text='关联的图稿，用于CTP制版，支持多个图稿（如纸卡双面印刷的面版和底版）', related_name='work_orders', to='workorder.artwork', verbose_name='图稿（CTP版）'),
        ),
    ]
