# Generated by Django 4.2.11 on 2026-01-20 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workorder", "0026_add_process_indexes"),
    ]

    operations = [
        migrations.AddField(
            model_name="department",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
        migrations.AlterField(
            model_name="department",
            name="code",
            field=models.CharField(
                help_text="部门编码，只能包含小写字母、数字和下划线",
                max_length=20,
                unique=True,
                verbose_name="部门编码",
            ),
        ),
        migrations.AlterField(
            model_name="department",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="禁用后部门将不可用于新的施工单",
                verbose_name="是否启用",
            ),
        ),
        migrations.AlterField(
            model_name="department",
            name="name",
            field=models.CharField(
                help_text="部门名称，必须唯一",
                max_length=50,
                unique=True,
                verbose_name="部门名称",
            ),
        ),
        migrations.AlterField(
            model_name="department",
            name="sort_order",
            field=models.IntegerField(
                default=0, help_text="排序值，数字越小越靠前", verbose_name="排序"
            ),
        ),
        migrations.AddIndex(
            model_name="department",
            index=models.Index(fields=["name"], name="department_name_idx"),
        ),
        migrations.AddIndex(
            model_name="department",
            index=models.Index(fields=["code"], name="department_code_idx"),
        ),
        migrations.AddIndex(
            model_name="department",
            index=models.Index(fields=["is_active"], name="department_is_active_idx"),
        ),
        migrations.AddIndex(
            model_name="department",
            index=models.Index(fields=["sort_order"], name="department_sort_order_idx"),
        ),
        migrations.AddIndex(
            model_name="department",
            index=models.Index(
                fields=["is_active", "sort_order"], name="dept_active_sort_idx"
            ),
        ),
    ]
