# Generated by Django 4.2.11 on 2026-01-21 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workorder", "0028_add_productgroup_indexes"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(fields=["name"], name="customer_name_idx"),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(fields=["phone"], name="customer_phone_idx"),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(fields=["salesperson"], name="customer_salesperson_idx"),
        ),
    ]
