# Generated by Django 4.2.8 on 2025-12-31 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0028_change_die_to_manytomany'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='defective_quantity',
            field=models.IntegerField(blank=True, help_text='单位：车', null=True, verbose_name='预损数量'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='production_quantity',
            field=models.IntegerField(blank=True, help_text='单位：车', null=True, verbose_name='生产数量'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='dies',
            field=models.ManyToManyField(blank=True, help_text='关联的刀模，用于模切工序，支持多个刀模', related_name='work_orders', to='workorder.die', verbose_name='刀模'),
        ),
    ]
