# Generated by Django 4.2.11 on 2026-01-21 23:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("workorder", "0029_customer_customer_name_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productstock",
            name="min_stock_level",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="库存低于此数量时触发预警",
                max_digits=10,
                verbose_name="最小库存",
            ),
        ),
        migrations.AddField(
            model_name="productstock",
            name="reserved_quantity",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="预留数量"
            ),
        ),
        migrations.AddField(
            model_name="productstock",
            name="unit_cost",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="单位成本"
            ),
        ),
        migrations.AlterField(
            model_name="die",
            name="code",
            field=models.CharField(
                blank=True,
                help_text="刀模唯一编码，留空则自动生成，格式：DIE + yyyymm + 3位序号",
                max_length=50,
                unique=True,
                verbose_name="刀模编码",
            ),
        ),
        migrations.AlterField(
            model_name="die",
            name="confirmed",
            field=models.BooleanField(
                default=False,
                help_text="设计部是否已确认该刀模，确认后关键字段不可修改",
                verbose_name="已确认",
            ),
        ),
        migrations.AlterField(
            model_name="die",
            name="confirmed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="刀模被确认的时间",
                null=True,
                verbose_name="确认时间",
            ),
        ),
        migrations.AlterField(
            model_name="die",
            name="confirmed_by",
            field=models.ForeignKey(
                blank=True,
                help_text="确认该刀模的用户",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="confirmed_dies",
                to=settings.AUTH_USER_MODEL,
                verbose_name="确认人",
            ),
        ),
        migrations.AlterField(
            model_name="die",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="刀模记录创建时间", verbose_name="创建时间"
            ),
        ),
        migrations.AlterField(
            model_name="die",
            name="material",
            field=models.CharField(
                blank=True,
                help_text="刀模材质，如：木板、胶板、钢板等",
                max_length=100,
                verbose_name="材质",
            ),
        ),
        migrations.AlterField(
            model_name="die",
            name="name",
            field=models.CharField(
                help_text="刀模的描述性名称，必填，最大200字符",
                max_length=200,
                verbose_name="刀模名称",
            ),
        ),
        migrations.AlterField(
            model_name="die",
            name="notes",
            field=models.TextField(
                blank=True, help_text="刀模的补充说明信息", verbose_name="备注"
            ),
        ),
        migrations.AlterField(
            model_name="die",
            name="size",
            field=models.CharField(
                blank=True,
                help_text="刀模尺寸规格，如：420x594mm、889x1194mm等",
                max_length=100,
                verbose_name="尺寸",
            ),
        ),
        migrations.AlterField(
            model_name="die",
            name="thickness",
            field=models.CharField(
                blank=True,
                help_text="刀模厚度，如：3mm、5mm等",
                max_length=50,
                verbose_name="厚度",
            ),
        ),
        migrations.AlterField(
            model_name="die",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="刀模记录最后更新时间", verbose_name="更新时间"
            ),
        ),
        migrations.AddIndex(
            model_name="artwork",
            index=models.Index(fields=["name"], name="artwork_name_idx"),
        ),
        migrations.AddIndex(
            model_name="artwork",
            index=models.Index(fields=["confirmed"], name="artwork_confirmed_idx"),
        ),
        migrations.AddIndex(
            model_name="artwork",
            index=models.Index(fields=["created_at"], name="artwork_created_idx"),
        ),
        migrations.AddIndex(
            model_name="die",
            index=models.Index(fields=["code"], name="die_code_idx"),
        ),
        migrations.AddIndex(
            model_name="die",
            index=models.Index(fields=["name"], name="die_name_idx"),
        ),
        migrations.AddIndex(
            model_name="die",
            index=models.Index(fields=["confirmed"], name="die_confirmed_idx"),
        ),
        migrations.AddIndex(
            model_name="die",
            index=models.Index(fields=["created_at"], name="die_created_idx"),
        ),
        migrations.AddIndex(
            model_name="embossingplate",
            index=models.Index(fields=["code"], name="embossing_plate_code_idx"),
        ),
        migrations.AddIndex(
            model_name="embossingplate",
            index=models.Index(fields=["name"], name="embossing_plate_name_idx"),
        ),
        migrations.AddIndex(
            model_name="embossingplate",
            index=models.Index(fields=["confirmed"], name="embossing_plate_conf_idx"),
        ),
        migrations.AddIndex(
            model_name="embossingplate",
            index=models.Index(
                fields=["created_at"], name="embossing_plate_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="foilingplate",
            index=models.Index(fields=["code"], name="foiling_plate_code_idx"),
        ),
        migrations.AddIndex(
            model_name="foilingplate",
            index=models.Index(fields=["name"], name="foiling_plate_name_idx"),
        ),
        migrations.AddIndex(
            model_name="foilingplate",
            index=models.Index(
                fields=["confirmed"], name="foiling_plate_confirmed_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="foilingplate",
            index=models.Index(fields=["created_at"], name="foiling_plate_created_idx"),
        ),
    ]
