# Generated by Django 4.2.8 on 2025-12-31 01:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workorder', '0029_add_production_and_defective_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='salesperson',
            field=models.ForeignKey(blank=True, help_text='负责该客户的业务员', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to=settings.AUTH_USER_MODEL, verbose_name='业务员'),
        ),
    ]
