# Generated by Django 4.2.8 on 2025-12-31 03:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workorder', '0030_add_salesperson_to_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='approval_comment',
            field=models.TextField(blank=True, help_text='业务员审核意见', verbose_name='审核意见'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='approval_status',
            field=models.CharField(choices=[('pending', '待审核'), ('approved', '已通过'), ('rejected', '已拒绝')], default='pending', max_length=20, verbose_name='审核状态'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='审核时间'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='业务员审核人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_orders', to=settings.AUTH_USER_MODEL, verbose_name='审核人'),
        ),
    ]
