# Generated by Django 4.2.11 on 2026-01-22 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workorder", "0030_add_productstock_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="die",
            name="die_type",
            field=models.CharField(
                choices=[
                    ("combined", "拼版刀模"),
                    ("dedicated", "专用刀模"),
                    ("universal", "通用刀模"),
                ],
                default="dedicated",
                help_text="拼版刀模：多产品同时切割；专用刀模：单产品专用；通用刀模：多产品可共用但每次只切一种",
                max_length=20,
                verbose_name="刀模类型",
            ),
        ),
        migrations.AddField(
            model_name="dieproduct",
            name="relation_type",
            field=models.CharField(
                choices=[("imposition", "拼版关系"), ("exclusive", "独占关系")],
                default="exclusive",
                help_text="拼版关系：与其他产品同时切割；独占关系：单独使用此刀模",
                max_length=20,
                verbose_name="关联类型",
            ),
        ),
        migrations.AlterField(
            model_name="dieproduct",
            name="quantity",
            field=models.IntegerField(
                default=1,
                help_text="该产品在刀模中的数量（每次模切产出数量）",
                verbose_name="数量",
            ),
        ),
    ]
