# Generated by Django 4.2.8 on 2025-12-31 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0031_add_approval_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='processes',
            field=models.ManyToManyField(blank=True, help_text='该部门负责的工序', to='workorder.process', verbose_name='工序'),
        ),
    ]
