# Generated by Django 4.2.11 on 2026-01-22 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("workorder", "0031_add_die_type_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="product_group",
            field=models.ForeignKey(
                blank=True,
                help_text="套装主产品和套装子产品需要关联产品组",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to="workorder.productgroup",
                verbose_name="所属产品组",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="product_type",
            field=models.CharField(
                choices=[
                    ("single", "单品"),
                    ("group_main", "套装主产品"),
                    ("group_item", "套装子产品"),
                ],
                default="single",
                help_text="单品可独立销售；套装主产品用于下单；套装子产品用于生产",
                max_length=20,
                verbose_name="产品类型",
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["product_type"], name="product_type_idx"),
        ),
    ]
