# Generated by Django 4.2.11 on 2026-01-22 10:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("workorder", "0032_add_product_type_field"),
    ]

    operations = [
        migrations.CreateModel(
            name="PurchaseReceiveRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "received_quantity",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="本次收货的数量",
                        max_digits=10,
                        verbose_name="收货数量",
                    ),
                ),
                (
                    "received_date",
                    models.DateField(
                        default=django.utils.timezone.now,
                        help_text="实际收货日期",
                        verbose_name="收货日期",
                    ),
                ),
                (
                    "delivery_note_number",
                    models.CharField(
                        blank=True,
                        help_text="供应商送货单号",
                        max_length=100,
                        verbose_name="送货单号",
                    ),
                ),
                (
                    "inspection_status",
                    models.CharField(
                        choices=[
                            ("pending", "待质检"),
                            ("qualified", "合格"),
                            ("unqualified", "不合格"),
                            ("partial_qualified", "部分合格"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="质检状态",
                    ),
                ),
                (
                    "qualified_quantity",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="质检合格的数量",
                        max_digits=10,
                        null=True,
                        verbose_name="合格数量",
                    ),
                ),
                (
                    "unqualified_quantity",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="质检不合格的数量",
                        max_digits=10,
                        null=True,
                        verbose_name="不合格数量",
                    ),
                ),
                (
                    "unqualified_reason",
                    models.TextField(
                        blank=True,
                        help_text="质检不合格的原因说明",
                        verbose_name="不合格原因",
                    ),
                ),
                (
                    "inspected_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="质检时间"
                    ),
                ),
                (
                    "is_stocked",
                    models.BooleanField(
                        default=False,
                        help_text="合格物料是否已入库",
                        verbose_name="已入库",
                    ),
                ),
                (
                    "stocked_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="入库时间"
                    ),
                ),
                (
                    "is_returned",
                    models.BooleanField(
                        default=False,
                        help_text="不合格物料是否已退货",
                        verbose_name="已退货",
                    ),
                ),
                (
                    "returned_quantity",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="退货数量",
                    ),
                ),
                (
                    "returned_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="退货时间"
                    ),
                ),
                ("return_note", models.TextField(blank=True, verbose_name="退货备注")),
                ("notes", models.TextField(blank=True, verbose_name="备注")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "inspected_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inspected_receive_records",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="质检人",
                    ),
                ),
                (
                    "purchase_order_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="receive_records",
                        to="workorder.purchaseorderitem",
                        verbose_name="采购单明细",
                    ),
                ),
                (
                    "received_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="purchase_receive_records",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="收货人",
                    ),
                ),
                (
                    "returned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="returned_receive_records",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="退货操作人",
                    ),
                ),
                (
                    "stocked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stocked_receive_records",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="入库操作人",
                    ),
                ),
            ],
            options={
                "verbose_name": "采购收货记录",
                "verbose_name_plural": "采购收货记录管理",
                "ordering": ["-received_date", "-created_at"],
                "indexes": [
                    models.Index(fields=["purchase_order_item"], name="prr_item_idx"),
                    models.Index(
                        fields=["inspection_status"], name="prr_insp_status_idx"
                    ),
                    models.Index(fields=["received_date"], name="prr_recv_date_idx"),
                    models.Index(fields=["is_stocked"], name="prr_stocked_idx"),
                ],
            },
        ),
    ]
