# Generated by Django 4.2.8 on 2025-12-31 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0032_add_processes_to_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workordermaterial',
            name='actual_quantity',
        ),
        migrations.RemoveField(
            model_name='workordermaterial',
            name='planned_quantity',
        ),
    ]
