# Generated by Django 4.2.11 on 2026-01-22 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("workorder", "0033_purchase_receive_record"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliveryitem",
            name="sales_order_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="delivery_items",
                to="workorder.salesorderitem",
                verbose_name="销售订单明细",
            ),
        ),
        migrations.AddField(
            model_name="salesorderitem",
            name="delivered_quantity",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="已通过发货单发出的数量",
                max_digits=10,
                verbose_name="已发货数量",
            ),
        ),
    ]
