# Generated by Django 4.2.8 on 2025-12-31 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0033_remove_planned_actual_quantity_from_workordermaterial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workorder',
            name='imposition_quantity',
        ),
    ]
