# Generated by Django 4.2.11 on 2026-02-01 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workorder", "0034_add_delivery_tracking_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="data",
            field=models.JSONField(blank=True, null=True, verbose_name="扩展数据"),
        ),
        migrations.AddField(
            model_name="notification",
            name="is_sent",
            field=models.BooleanField(default=False, verbose_name="已发送"),
        ),
        migrations.AlterField(
            model_name="salesorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "草稿"),
                    ("submitted", "已提交"),
                    ("approved", "已审核"),
                    ("rejected", "已拒绝"),
                    ("in_production", "生产中"),
                    ("completed", "已完成"),
                    ("cancelled", "已取消"),
                ],
                default="draft",
                max_length=20,
                verbose_name="订单状态",
            ),
        ),
        migrations.AlterField(
            model_name="salesorder",
            name="tax_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="税率百分比，如13表示13%",
                max_digits=5,
                verbose_name="税率",
            ),
        ),
        migrations.AlterField(
            model_name="workordertask",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "草稿"),
                    ("pending", "待开始"),
                    ("in_progress", "进行中"),
                    ("completed", "已完成"),
                    ("cancelled", "已取消"),
                ],
                default="pending",
                max_length=20,
                verbose_name="状态",
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["created_at"], name="workorder_n_created_b2cdd4_idx"
            ),
        ),
    ]
