# Generated by Django 4.2.11 on 2026-02-01 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workorder", "0035_notification_data_notification_is_sent_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="workordertask",
            index=models.Index(
                fields=["assigned_department", "status", "task_type"],
                name="task_dept_status_type_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="workordertask",
            index=models.Index(
                fields=["assigned_operator", "status"], name="task_operator_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workordertask",
            index=models.Index(
                fields=["status", "created_at"], name="task_status_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workordertask",
            index=models.Index(
                fields=["work_order_process", "status", "task_type"],
                name="task_process_status_type_idx",
            ),
        ),
    ]
