# Generated by Django 4.2.11 on 2026-03-04 01:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("contenttypes", "0002_remove_content_type_name"),
        ("workorder", "0036_add_performance_indexes"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="日志ID",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("create", "创建"),
                            ("update", "更新"),
                            ("delete", "删除"),
                            ("view", "查看"),
                            ("export", "导出"),
                            ("import", "导入"),
                            ("approve", "审核通过"),
                            ("reject", "审核拒绝"),
                            ("login", "登录"),
                            ("logout", "登出"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="操作类型",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="用户名快照"
                    ),
                ),
                (
                    "object_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=255,
                        null=True,
                        verbose_name="对象ID",
                    ),
                ),
                (
                    "object_repr",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="对象表示"
                    ),
                ),
                (
                    "changes",
                    models.JSONField(
                        default=dict,
                        help_text="记录变更前后的数据对比",
                        verbose_name="变更数据",
                    ),
                ),
                (
                    "changed_fields",
                    models.JSONField(default=list, verbose_name="变更字段"),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP地址"
                    ),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="用户代理")),
                (
                    "request_method",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="请求方法"
                    ),
                ),
                ("request_path", models.TextField(blank=True, verbose_name="请求路径")),
                (
                    "extra_context",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="存储额外的上下文信息，如业务逻辑相关数据",
                        verbose_name="额外上下文",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="创建时间",
                    ),
                ),
            ],
            options={
                "verbose_name": "审计日志",
                "verbose_name_plural": "审计日志",
                "db_table": "audit_log",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AuditLogExport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                (
                    "filters",
                    models.JSONField(default=dict, help_text="导出时使用的过滤条件"),
                ),
                ("file_path", models.CharField(blank=True, max_length=512)),
                ("record_count", models.IntegerField(default=0)),
                (
                    "file_size",
                    models.IntegerField(default=0, help_text="文件大小（字节）"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待处理"),
                            ("processing", "处理中"),
                            ("completed", "已完成"),
                            ("failed", "失败"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "审计日志导出",
                "verbose_name_plural": "审计日志导出",
                "db_table": "audit_log_export",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AuditLogSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "retention_days",
                    models.IntegerField(
                        default=365,
                        help_text="日志保留天数，超过此天数的日志将被自动清理",
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(default=True, help_text="是否启用审计日志功能"),
                ),
                (
                    "log_login",
                    models.BooleanField(default=True, verbose_name="记录登录"),
                ),
                (
                    "log_logout",
                    models.BooleanField(default=True, verbose_name="记录登出"),
                ),
                (
                    "log_export",
                    models.BooleanField(default=True, verbose_name="记录导出"),
                ),
                (
                    "log_import",
                    models.BooleanField(default=True, verbose_name="记录导入"),
                ),
                (
                    "async_write",
                    models.BooleanField(
                        default=True, help_text="异步写入日志，提高性能"
                    ),
                ),
                (
                    "audited_models",
                    models.JSONField(
                        default=list, help_text="需要审计的模型列表（格式：app.Model）"
                    ),
                ),
                (
                    "excluded_fields",
                    models.JSONField(
                        default=list, help_text="不需要审计的字段列表（如：last_login）"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "审计日志配置",
                "verbose_name_plural": "审计日志配置",
                "db_table": "audit_log_settings",
            },
        ),
        migrations.AddIndex(
            model_name="tasklog",
            index=models.Index(
                fields=["log_type", "created_at"], name="workorder_t_log_typ_ba72d8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tasklog",
            index=models.Index(
                fields=["operator", "created_at"], name="workorder_t_operato_496958_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tasklog",
            index=models.Index(
                fields=["task", "created_at"], name="workorder_t_task_id_725a5b_idx"
            ),
        ),
        migrations.AddField(
            model_name="auditlogexport",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="audit_log_exports",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="content_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
                verbose_name="内容类型",
            ),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="audit_logs",
                to=settings.AUTH_USER_MODEL,
                verbose_name="操作用户",
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["user", "-created_at"], name="audit_log_user_id_b57afc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["content_type", "object_id"],
                name="audit_log_content_10f046_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["action_type", "-created_at"],
                name="audit_log_action__2f922d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["-created_at"], name="audit_log_created_e49a79_idx"
            ),
        ),
    ]
