# Generated by Codex on 2026-03-16

from django.apps import apps as global_apps
from django.contrib.auth.management import create_permissions
from django.db import migrations


def seed_additional_groups_forward(apps, schema_editor):
    app_config = global_apps.get_app_config("workorder")
    create_permissions(
        app_config,
        verbosity=0,
        using=schema_editor.connection.alias,
        apps=apps,
    )

    Group = apps.get_model("auth", "Group")
    Permission = apps.get_model("auth", "Permission")
    ContentType = apps.get_model("contenttypes", "ContentType")
    WorkOrder = apps.get_model("workorder", "WorkOrder")

    def get_perm(action, model):
        try:
            content_type = ContentType.objects.get_for_model(model)
        except ContentType.DoesNotExist:
            return None
        codename = f"{action}_{model._meta.model_name}"
        try:
            return Permission.objects.get(
                content_type=content_type,
                codename=codename,
            )
        except Permission.DoesNotExist:
            return None

    perms_view = [get_perm("view", WorkOrder)]
    perms_change = [get_perm("change", WorkOrder)]

    role_permissions = {
        "主管": perms_view + perms_change,
        "经理": perms_view + perms_change,
        "supervisor": perms_view + perms_change,
        "操作员": perms_view,
    }

    for group_name, perms in role_permissions.items():
        group, _ = Group.objects.get_or_create(name=group_name)
        for perm in perms:
            if perm and perm not in group.permissions.all():
                group.permissions.add(perm)


def seed_additional_groups_backward(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    preset_groups = ["主管", "经理", "supervisor", "操作员"]
    Group.objects.filter(name__in=preset_groups).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("workorder", "0037_add_audit_log_models"),
    ]

    operations = [
        migrations.RunPython(
            seed_additional_groups_forward,
            seed_additional_groups_backward,
        ),
    ]
