# Generated by Codex on 2026-03-16

from django.apps import apps as global_apps
from django.contrib.auth.management import create_permissions
from django.db import migrations


def update_group_permissions_forward(apps, schema_editor):
    app_config = global_apps.get_app_config("workorder")
    create_permissions(
        app_config,
        verbosity=0,
        using=schema_editor.connection.alias,
        apps=apps,
    )

    Group = apps.get_model("auth", "Group")
    Permission = apps.get_model("auth", "Permission")
    ContentType = apps.get_model("contenttypes", "ContentType")

    def get_model(name):
        try:
            return apps.get_model("workorder", name)
        except LookupError:
            return None

    def get_perm(action, model):
        if model is None:
            return None
        try:
            content_type = ContentType.objects.get_for_model(model)
        except ContentType.DoesNotExist:
            return None
        codename = f"{action}_{model._meta.model_name}"
        try:
            return Permission.objects.get(
                content_type=content_type,
                codename=codename,
            )
        except Permission.DoesNotExist:
            return None

    def add_group_permissions(group_name, model_actions):
        group, _ = Group.objects.get_or_create(name=group_name)
        for model_name, actions in model_actions.items():
            model = get_model(model_name)
            for action in actions:
                perm = get_perm(action, model)
                if perm and perm not in group.permissions.all():
                    group.permissions.add(perm)

    role_permissions = {
        "业务员": {
            "WorkOrder": ["add", "view", "change"],
            "SalesOrder": ["add", "view", "change"],
            "SalesOrderItem": ["add", "view", "change"],
            "Customer": ["add", "view", "change"],
            "Process": ["view"],
            "Department": ["view"],
            "Product": ["view"],
            "ProductGroup": ["view"],
            "ProductGroupItem": ["view"],
            "ProductMaterial": ["view"],
            "Material": ["view"],
            "Supplier": ["view"],
            "MaterialSupplier": ["view"],
            "Artwork": ["view"],
            "ArtworkProduct": ["view"],
            "Die": ["view"],
            "DieProduct": ["view"],
            "FoilingPlate": ["view"],
            "FoilingPlateProduct": ["view"],
            "EmbossingPlate": ["view"],
            "EmbossingPlateProduct": ["view"],
            "DeliveryOrder": ["view"],
            "DeliveryItem": ["view"],
            "Invoice": ["view"],
            "Payment": ["view"],
            "PaymentPlan": ["view"],
            "Statement": ["view"],
        },
        "主管": {
            "WorkOrder": ["view", "change"],
            "WorkOrderProcess": ["view", "change"],
            "WorkOrderTask": ["view", "change"],
            "WorkOrderMaterial": ["view", "change"],
            "WorkOrderProduct": ["view", "change"],
            "ProcessLog": ["view"],
            "TaskLog": ["view"],
            "Process": ["view"],
            "Department": ["view"],
            "Product": ["view"],
            "Material": ["view"],
            "Supplier": ["view"],
            "PurchaseOrder": ["view", "change"],
            "PurchaseOrderItem": ["view", "change"],
            "PurchaseReceiveRecord": ["view", "change"],
            "ProductStock": ["view", "change"],
            "StockIn": ["view", "change"],
            "StockOut": ["view", "change"],
            "DeliveryOrder": ["view", "change"],
            "DeliveryItem": ["view", "change"],
            "QualityInspection": ["view", "change"],
            "SalesOrder": ["view"],
            "Invoice": ["view", "change"],
            "Payment": ["view", "change"],
            "PaymentPlan": ["view", "change"],
            "Statement": ["view", "change"],
            "ProductionCost": ["view", "change"],
            "TaskAssignmentRule": ["view", "change"],
        },
        "supervisor": {
            "WorkOrder": ["view", "change"],
            "WorkOrderProcess": ["view", "change"],
            "WorkOrderTask": ["view", "change"],
            "WorkOrderMaterial": ["view", "change"],
            "WorkOrderProduct": ["view", "change"],
            "ProcessLog": ["view"],
            "TaskLog": ["view"],
            "Process": ["view"],
            "Department": ["view"],
            "Product": ["view"],
            "Material": ["view"],
            "Supplier": ["view"],
            "PurchaseOrder": ["view", "change"],
            "PurchaseOrderItem": ["view", "change"],
            "PurchaseReceiveRecord": ["view", "change"],
            "ProductStock": ["view", "change"],
            "StockIn": ["view", "change"],
            "StockOut": ["view", "change"],
            "DeliveryOrder": ["view", "change"],
            "DeliveryItem": ["view", "change"],
            "QualityInspection": ["view", "change"],
            "SalesOrder": ["view"],
            "Invoice": ["view", "change"],
            "Payment": ["view", "change"],
            "PaymentPlan": ["view", "change"],
            "Statement": ["view", "change"],
            "ProductionCost": ["view", "change"],
            "TaskAssignmentRule": ["view", "change"],
        },
        "经理": {
            "WorkOrder": ["view", "change"],
            "WorkOrderProcess": ["view", "change"],
            "WorkOrderTask": ["view", "change"],
            "WorkOrderMaterial": ["view", "change"],
            "WorkOrderProduct": ["view", "change"],
            "ProcessLog": ["view"],
            "TaskLog": ["view"],
            "Process": ["view"],
            "Department": ["view"],
            "Product": ["view", "change"],
            "Material": ["view", "change"],
            "Supplier": ["view", "change"],
            "PurchaseOrder": ["view", "change"],
            "PurchaseOrderItem": ["view", "change"],
            "PurchaseReceiveRecord": ["view", "change"],
            "ProductStock": ["view", "change"],
            "StockIn": ["view", "change"],
            "StockOut": ["view", "change"],
            "DeliveryOrder": ["view", "change"],
            "DeliveryItem": ["view", "change"],
            "QualityInspection": ["view", "change"],
            "SalesOrder": ["view", "change"],
            "Invoice": ["view", "change"],
            "Payment": ["view", "change"],
            "PaymentPlan": ["view", "change"],
            "Statement": ["view", "change"],
            "ProductionCost": ["view", "change"],
            "CostCenter": ["view", "change"],
            "CostItem": ["view", "change"],
            "ApprovalWorkflow": ["view", "change"],
            "ApprovalStep": ["view", "change"],
            "ApprovalRule": ["view", "change"],
            "ApprovalEscalation": ["view", "change"],
            "TaskAssignmentRule": ["view", "change"],
            "AuditLog": ["view"],
            "AuditLogExport": ["view"],
            "AuditLogSettings": ["view", "change"],
        },
        "操作员": {
            "WorkOrder": ["view"],
            "WorkOrderTask": ["view", "change"],
            "Process": ["view"],
            "Department": ["view"],
            "Product": ["view"],
            "Material": ["view"],
            "ProductStock": ["view"],
            "StockIn": ["view"],
            "StockOut": ["view"],
        },
    }

    for group_name, model_actions in role_permissions.items():
        add_group_permissions(group_name, model_actions)


def update_group_permissions_backward(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Permission = apps.get_model("auth", "Permission")

    groups = [
        "业务员",
        "主管",
        "经理",
        "supervisor",
        "操作员",
    ]

    for group_name in groups:
        group = Group.objects.filter(name=group_name).first()
        if not group:
            continue
        # 回滚时仅移除本迁移可能添加的权限（按 workorder 应用权限清理）
        perms = Permission.objects.filter(content_type__app_label="workorder")
        group.permissions.remove(*perms)


class Migration(migrations.Migration):
    dependencies = [
        ("workorder", "0038_seed_additional_groups"),
    ]

    operations = [
        migrations.RunPython(
            update_group_permissions_forward,
            update_group_permissions_backward,
        ),
    ]
