# Generated by Codex on 2026-03-16

from django.apps import apps as global_apps
from django.contrib.auth.management import create_permissions
from django.db import migrations


def seed_english_groups_forward(apps, schema_editor):
    app_config = global_apps.get_app_config("workorder")
    create_permissions(
        app_config,
        verbosity=0,
        using=schema_editor.connection.alias,
        apps=apps,
    )

    Group = apps.get_model("auth", "Group")

    # Map English groups to existing Chinese groups to keep permissions aligned.
    group_mapping = {
        "salespersons": "业务员",
        "operators": "操作员",
        "managers": "经理",
        "administrators": "经理",
    }

    for english_name, source_name in group_mapping.items():
        english_group, _ = Group.objects.get_or_create(name=english_name)
        source_group = Group.objects.filter(name=source_name).first()
        if not source_group:
            continue
        for perm in source_group.permissions.all():
            if perm not in english_group.permissions.all():
                english_group.permissions.add(perm)


def seed_english_groups_backward(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    preset_groups = ["salespersons", "operators", "managers", "administrators"]
    Group.objects.filter(name__in=preset_groups).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("workorder", "0039_update_group_permissions_matrix"),
    ]

    operations = [
        migrations.RunPython(
            seed_english_groups_forward,
            seed_english_groups_backward,
        ),
    ]
