# Generated by Django 4.2.11 on 2026-04-11 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0042_artwork_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoilingPlateImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('image', models.ImageField(help_text='支持 JPG、PNG、WebP 等常见图片格式', upload_to='foiling_plate_images/', verbose_name='图片文件')),
                ('sort_order', models.IntegerField(default=0, help_text='数值越小排越前', verbose_name='排序')),
                ('description', models.CharField(blank=True, help_text='如：正面、背面、烫金效果等', max_length=200, verbose_name='描述')),
                ('foiling_plate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='workorder.foilingplate', verbose_name='烫金版')),
            ],
            options={
                'verbose_name': '烫金版图片',
                'verbose_name_plural': '烫金版图片',
                'ordering': ['foiling_plate', 'sort_order'],
                'indexes': [models.Index(fields=['foiling_plate'], name='foiling_plate_image_idx')],
            },
        ),
        migrations.CreateModel(
            name='EmbossingPlateImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('image', models.ImageField(help_text='支持 JPG、PNG、WebP 等常见图片格式', upload_to='embossing_plate_images/', verbose_name='图片文件')),
                ('sort_order', models.IntegerField(default=0, help_text='数值越小排越前', verbose_name='排序')),
                ('description', models.CharField(blank=True, help_text='如：正面、背面、压凸效果等', max_length=200, verbose_name='描述')),
                ('embossing_plate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='workorder.embossingplate', verbose_name='压凸版')),
            ],
            options={
                'verbose_name': '压凸版图片',
                'verbose_name_plural': '压凸版图片',
                'ordering': ['embossing_plate', 'sort_order'],
                'indexes': [models.Index(fields=['embossing_plate'], name='embossing_plate_image_idx')],
            },
        ),
        migrations.CreateModel(
            name='DieImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('image', models.ImageField(help_text='支持 JPG、PNG、WebP 等常见图片格式', upload_to='die_images/', verbose_name='图片文件')),
                ('sort_order', models.IntegerField(default=0, help_text='数值越小排越前', verbose_name='排序')),
                ('description', models.CharField(blank=True, help_text='如：正面、背面、线刀图等', max_length=200, verbose_name='描述')),
                ('die', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='workorder.die', verbose_name='刀模')),
            ],
            options={
                'verbose_name': '刀模图片',
                'verbose_name_plural': '刀模图片',
                'ordering': ['die', 'sort_order'],
                'indexes': [models.Index(fields=['die'], name='die_image_die_idx')],
            },
        ),
    ]
