# Generated by Django 4.2.11 on 2026-05-07 09:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import workorder.models.system


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workorder', '0050_workorderproduct_source_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorderprocess',
            name='process_snapshot',
            field=models.JSONField(blank=True, help_text='工序的完整快照数据，包括名称、编码、部门等，用于追溯创建时的配置', null=True, verbose_name='工序快照'),
        ),
        migrations.AddField(
            model_name='workorderprocess',
            name='source_product_process_id',
            field=models.IntegerField(blank=True, help_text='如果工序来源于产品的默认工序配置，记录来源配置ID', null=True, verbose_name='来源产品工序配置ID'),
        ),
        migrations.AddField(
            model_name='workorderprocess',
            name='source_version',
            field=models.CharField(blank=True, help_text='来源产品工序配置的版本号', max_length=50, null=True, verbose_name='来源版本'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('workorder_created', '施工单创建'), ('workorder_updated', '施工单更新'), ('approval_passed', '审核通过'), ('approval_rejected', '审核拒绝'), ('approval_requested', '请求审核'), ('reapproval_requested', '请求重新审核'), ('task_assigned', '任务分派'), ('task_started', '任务开始'), ('task_overdue', '任务逾期'), ('task_due_soon', '任务即将到期'), ('process_completed', '工序完成'), ('workorder_completed', '施工单完成'), ('task_cancelled', '任务取消'), ('purchase_order_submitted', '采购单待审核'), ('purchase_order_approved', '采购单已批准'), ('purchase_order_rejected', '采购单已拒绝'), ('purchase_order_received', '采购单已收货'), ('low_stock_warning', '库存不足预警'), ('system', '系统通知')], max_length=30, verbose_name='通知类型'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='notification_preferences',
            field=models.JSONField(blank=True, default=workorder.models.system.default_user_notification_preferences, help_text='用户级通知开关、紧急阈值和免打扰时间段配置', verbose_name='通知偏好设置'),
        ),
        migrations.CreateModel(
            name='MaterialStockLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.CharField(choices=[('add', '增加'), ('reduce', '减少'), ('cut_consume', '开料消耗'), ('initial', '初始库存'), ('adjustment', '调整'), ('stocktake', '盘点')], help_text='库存变更类型', max_length=20, verbose_name='变更类型')),
                ('quantity', models.DecimalField(decimal_places=3, help_text='变更数量（正数为增加，负数为减少）', max_digits=12, verbose_name='变更数量')),
                ('old_quantity', models.DecimalField(decimal_places=3, help_text='变更前的库存数量', max_digits=12, verbose_name='变更前库存')),
                ('new_quantity', models.DecimalField(decimal_places=3, help_text='变更后的库存数量', max_digits=12, verbose_name='变更后库存')),
                ('reason', models.TextField(blank=True, help_text='库存变更的原因说明', verbose_name='变更原因')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_stock_logs', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_logs', to='workorder.material', verbose_name='物料')),
                ('work_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_stock_logs', to='workorder.workorder', verbose_name='关联施工单')),
            ],
            options={
                'verbose_name': '物料库存变更日志',
                'verbose_name_plural': '物料库存变更日志',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['material', 'created_at'], name='workorder_m_materia_cc901c_idx'), models.Index(fields=['change_type'], name='workorder_m_change__b5a8d7_idx'), models.Index(fields=['work_order'], name='workorder_m_work_or_0edbb9_idx')],
            },
        ),
        migrations.CreateModel(
            name='DraftTaskArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived_tasks_data', models.JSONField(help_text='存储草稿任务的完整数据快照，用于追溯和恢复', verbose_name='归档任务数据')),
                ('archive_reason', models.CharField(default='approval_rejected', help_text='归档原因，如：approval_rejected, manual_archive 等', max_length=50, verbose_name='归档原因')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='归档时间')),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_draft_tasks', to=settings.AUTH_USER_MODEL, verbose_name='归档操作人')),
                ('rejection_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_draft_tasks', to='workorder.workorderapprovallog', verbose_name='拒绝日志')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draft_task_archives', to='workorder.workorder', verbose_name='施工单')),
            ],
            options={
                'verbose_name': '草稿任务归档',
                'verbose_name_plural': '草稿任务归档',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['work_order', 'created_at'], name='workorder_d_work_or_bbf113_idx'), models.Index(fields=['archive_reason'], name='workorder_d_archive_d608bf_idx')],
            },
        ),
    ]
