# Generated by Django 4.2.11 on 2026-05-08 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0052_simplify_workorder_approval_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorderapprovallog',
            name='approval_status',
            field=models.CharField(choices=[('draft', '草稿'), ('submitted', '待审核'), ('approved', '已通过'), ('rejected', '已拒绝')], max_length=20, verbose_name='审核状态'),
        ),
        migrations.AlterField(
            model_name='workordertask',
            name='status',
            field=models.CharField(choices=[('pending', '待开始'), ('in_progress', '进行中'), ('completed', '已完成'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态'),
        ),
    ]
