# Generated by Django 4.2.11 on 2026-05-08 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0053_alter_workorderapprovallog_approval_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approvalrule',
            name='created_by',
        ),
        migrations.AlterUniqueTogether(
            name='approvalstep',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='approvalstep',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='approvalstep',
            name='work_order',
        ),
        migrations.RemoveField(
            model_name='approvalstep',
            name='workflow',
        ),
        migrations.RemoveField(
            model_name='approvalworkflow',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='current_workflow',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='multi_level_approval_enabled',
        ),
        migrations.DeleteModel(
            name='ApprovalEscalation',
        ),
        migrations.DeleteModel(
            name='ApprovalRule',
        ),
        migrations.DeleteModel(
            name='ApprovalStep',
        ),
        migrations.DeleteModel(
            name='ApprovalWorkflow',
        ),
    ]
