# Generated by Codex on 2026-05-12

from django.apps import apps as global_apps
from django.contrib.auth.management import create_permissions
from django.db import migrations


ROLE_PERMISSIONS = {
    "sales": {
        "WorkOrder": ["add", "view", "change"],
        "SalesOrder": ["add", "view", "change"],
        "SalesOrderItem": ["add", "view", "change"],
        "Customer": ["add", "view", "change"],
        "Process": ["view"],
        "Department": ["view"],
        "Product": ["add", "view", "change"],
        "ProductGroup": ["view"],
        "ProductGroupItem": ["view"],
        "ProductMaterial": ["view"],
        "Material": ["add", "view", "change"],
        "Supplier": ["view"],
        "MaterialSupplier": ["view"],
        "Artwork": ["add", "view", "change"],
        "ArtworkProduct": ["view"],
        "Die": ["view"],
        "DieProduct": ["view"],
        "FoilingPlate": ["add", "view", "change"],
        "FoilingPlateProduct": ["view"],
        "EmbossingPlate": ["add", "view", "change"],
        "EmbossingPlateProduct": ["view"],
        "DeliveryOrder": ["add", "view", "change"],
        "DeliveryItem": ["view"],
        "Invoice": ["view"],
        "Payment": ["view"],
        "PaymentPlan": ["view"],
        "Statement": ["view"],
    },
    "supervisor": {
        "WorkOrder": ["view", "change"],
        "WorkOrderProcess": ["view", "change"],
        "WorkOrderTask": ["view", "change"],
        "WorkOrderMaterial": ["view", "change"],
        "WorkOrderProduct": ["view", "change"],
        "ProcessLog": ["view"],
        "TaskLog": ["view"],
        "Process": ["view"],
        "Department": ["view"],
        "Product": ["view"],
        "Material": ["view"],
        "Supplier": ["view"],
        "PurchaseOrder": ["view", "change"],
        "PurchaseOrderItem": ["view", "change"],
        "PurchaseReceiveRecord": ["view", "change"],
        "ProductStock": ["view", "change"],
        "StockIn": ["view", "change"],
        "StockOut": ["view", "change"],
        "DeliveryOrder": ["view", "change"],
        "DeliveryItem": ["view", "change"],
        "QualityInspection": ["view", "change"],
        "SalesOrder": ["view"],
        "Invoice": ["view"],
        "Payment": ["view"],
        "PaymentPlan": ["view"],
        "Statement": ["view"],
        "ProductionCost": ["view"],
        "TaskAssignmentRule": ["view", "change"],
    },
    "manager": {
        "WorkOrder": ["view", "change"],
        "WorkOrderProcess": ["view", "change"],
        "WorkOrderTask": ["view", "change"],
        "WorkOrderMaterial": ["view", "change"],
        "WorkOrderProduct": ["view", "change"],
        "ProcessLog": ["view"],
        "TaskLog": ["view"],
        "Process": ["view"],
        "Department": ["view"],
        "Product": ["add", "view", "change"],
        "Material": ["add", "view", "change"],
        "Supplier": ["add", "view", "change"],
        "PurchaseOrder": ["view", "change"],
        "PurchaseOrderItem": ["view", "change"],
        "PurchaseReceiveRecord": ["view", "change"],
        "ProductStock": ["view", "change"],
        "StockIn": ["view", "change"],
        "StockOut": ["view", "change"],
        "DeliveryOrder": ["add", "view", "change"],
        "DeliveryItem": ["view", "change"],
        "QualityInspection": ["view", "change"],
        "SalesOrder": ["view", "change"],
        "Invoice": ["view", "change"],
        "Payment": ["view", "change"],
        "PaymentPlan": ["view", "change"],
        "Statement": ["view", "change"],
        "ProductionCost": ["view", "change"],
        "CostCenter": ["view", "change"],
        "CostItem": ["view", "change"],
        "TaskAssignmentRule": ["view", "change"],
        "AuditLog": ["view"],
        "AuditLogExport": ["view"],
        "AuditLogSettings": ["view", "change"],
    },
    "operator": {
        "WorkOrder": ["view"],
        "WorkOrderTask": ["view", "change"],
        "Process": ["view"],
        "Department": ["view"],
        "Product": ["view"],
        "Material": ["view"],
        "ProductStock": ["view"],
        "StockIn": ["view"],
        "StockOut": ["view"],
    },
    "finance": {
        "SalesOrder": ["view"],
        "Customer": ["view"],
        "Supplier": ["add", "view", "change"],
        "Invoice": ["add", "view", "change"],
        "Payment": ["add", "view", "change"],
        "PaymentPlan": ["view", "change"],
        "Statement": ["add", "view", "change"],
        "ProductionCost": ["view", "change"],
        "CostCenter": ["view", "change"],
        "CostItem": ["view", "change"],
    },
    "inventory": {
        "WorkOrder": ["view"],
        "SalesOrder": ["view"],
        "Product": ["view"],
        "Material": ["view"],
        "ProductStock": ["view", "change"],
        "StockIn": ["add", "view", "change"],
        "StockOut": ["add", "view", "change"],
        "DeliveryOrder": ["add", "view", "change"],
        "DeliveryItem": ["view", "change"],
        "PurchaseReceiveRecord": ["view", "change"],
    },
    "quality": {
        "WorkOrder": ["view"],
        "WorkOrderTask": ["view"],
        "Product": ["view"],
        "Material": ["view"],
        "QualityInspection": ["add", "view", "change"],
        "PurchaseReceiveRecord": ["view", "change"],
        "ProductStock": ["view"],
        "StockIn": ["view"],
    },
    "admin": {
        "Customer": ["view", "change", "delete"],
        "Supplier": ["view", "change"],
        "Department": ["add", "view", "change"],
        "Process": ["add", "view", "change"],
        "TaskAssignmentRule": ["add", "view", "change"],
        "SystemNotificationSettings": ["view", "change"],
        "NotificationTemplate": ["add", "view", "change", "delete"],
        "Notification": ["view", "change"],
        "AuditLog": ["view"],
        "AuditLogExport": ["view"],
        "AuditLogSettings": ["view", "change"],
    },
}

ROLE_CUSTOM_PERMISSIONS = {
    "manager": {
        "WorkOrder": ["change_approved_workorder", "delete_workorder"],
        "SalesOrder": ["change_approved_salesorder"],
    },
}

ROLE_ALIASES = {
    "业务员": "sales",
    "主管": "supervisor",
    "经理": "manager",
    "操作员": "operator",
    "财务": "finance",
    "仓储": "inventory",
    "质检": "quality",
    "系统管理员": "admin",
    "salespersons": "sales",
    "operators": "operator",
    "managers": "manager",
    "administrators": "admin",
    "warehouse": "inventory",
}

STALE_PERMISSION_MODELS = {
    "approvalworkflow",
    "approvalstep",
    "approvalrule",
    "approvalescalation",
}


def normalize_role_groups_forward(apps, schema_editor):
    app_config = global_apps.get_app_config("workorder")
    create_permissions(
        app_config,
        verbosity=0,
        using=schema_editor.connection.alias,
        apps=apps,
    )

    Group = apps.get_model("auth", "Group")
    Permission = apps.get_model("auth", "Permission")
    ContentType = apps.get_model("contenttypes", "ContentType")

    def get_model(model_name):
        try:
            return apps.get_model("workorder", model_name)
        except LookupError:
            return None

    def get_default_perm(action, model_name):
        model = get_model(model_name)
        if model is None:
            return None
        try:
            content_type = ContentType.objects.get_for_model(model)
        except ContentType.DoesNotExist:
            return None
        codename = f"{action}_{model._meta.model_name}"
        return Permission.objects.filter(
            content_type=content_type,
            codename=codename,
        ).first()

    def get_custom_perm(codename, model_name):
        model = get_model(model_name)
        if model is None:
            return None
        try:
            content_type = ContentType.objects.get_for_model(model)
        except ContentType.DoesNotExist:
            return None
        return Permission.objects.filter(
            content_type=content_type,
            codename=codename,
        ).first()

    for role_name, model_actions in ROLE_PERMISSIONS.items():
        group, _ = Group.objects.get_or_create(name=role_name)
        group.permissions.clear()
        for model_name, actions in model_actions.items():
            for action in actions:
                permission = get_default_perm(action, model_name)
                if permission:
                    group.permissions.add(permission)
        for model_name, codenames in ROLE_CUSTOM_PERMISSIONS.get(role_name, {}).items():
            for codename in codenames:
                permission = get_custom_perm(codename, model_name)
                if permission:
                    group.permissions.add(permission)

    for alias_name, target_name in ROLE_ALIASES.items():
        alias_group = Group.objects.filter(name=alias_name).first()
        target_group = Group.objects.filter(name=target_name).first()
        if not alias_group or not target_group:
            continue
        for user in alias_group.user_set.all():
            target_group.user_set.add(user)
        alias_group.delete()

    stale_content_types = ContentType.objects.filter(
        app_label="workorder",
        model__in=STALE_PERMISSION_MODELS,
    )
    Permission.objects.filter(content_type__in=stale_content_types).delete()
    stale_content_types.delete()


class Migration(migrations.Migration):
    dependencies = [
        ("workorder", "0054_remove_multi_level_approval"),
    ]

    operations = [
        migrations.RunPython(
            normalize_role_groups_forward,
            migrations.RunPython.noop,
        ),
    ]
