# Generated by Codex on 2026-05-12

from django.db import migrations


def migrate_group_names_forward(apps, schema_editor):
    """
    将 auth_group 表中的中文组名迁移为英文 code。

    映射关系:
      业务员 → sales
      主管 → supervisor
      经理 → manager
      操作员 → operator
      财务 → finance
      仓储 → inventory
      质检 → quality
      系统管理员 → admin

    别名合并:
      salespersons → sales
      operators → operator
      managers → manager
      administrators → admin
      supervisor → supervisor
      warehouse → inventory
    """
    Group = apps.get_model('auth', 'Group')

    name_mapping = {
        # 中文名 → 英文 code
        '业务员': 'sales',
        '主管': 'supervisor',
        '经理': 'manager',
        '操作员': 'operator',
        '财务': 'finance',
        '仓储': 'inventory',
        '质检': 'quality',
        '系统管理员': 'admin',
        # 英文别名 → 标准 code
        'salespersons': 'sales',
        'operators': 'operator',
        'managers': 'manager',
        'administrators': 'admin',
        'supervisor': 'supervisor',
        'warehouse': 'inventory',
    }

    for old_name, new_name in name_mapping.items():
        updated = Group.objects.filter(name=old_name).update(name=new_name)
        if updated:
            print(f"Migrated group: {old_name} → {new_name}")


def migrate_group_names_backward(apps, schema_editor):
    """
    回滚：将英文 code 恢复为中文名。
    仅恢复主要角色，别名不回滚。
    """
    Group = apps.get_model('auth', 'Group')

    code_to_chinese = {
        'sales': '业务员',
        'supervisor': '主管',
        'manager': '经理',
        'operator': '操作员',
        'finance': '财务',
        'inventory': '仓储',
        'quality': '质检',
        'admin': '系统管理员',
    }

    for code, chinese in code_to_chinese.items():
        updated = Group.objects.filter(name=code).update(name=chinese)
        if updated:
            print(f"Rolled back group: {code} → {chinese}")


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0055_normalize_role_groups'),
    ]

    operations = [
        migrations.RunPython(
            migrate_group_names_forward,
            migrate_group_names_backward,
        ),
    ]