# Generated by Django 4.2.11 on 2026-05-29 08:43

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("workorder", "0059_finalize_warehouse_department"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="salesorder",
            options={
                "ordering": ["-created_at"],
                "permissions": [
                    ("change_approved_salesorder", "可以编辑已审核的客户订单")
                ],
                "verbose_name": "客户订单",
                "verbose_name_plural": "客户订单管理",
            },
        ),
        migrations.AlterModelOptions(
            name="salesorderitem",
            options={
                "ordering": ["sales_order", "id"],
                "verbose_name": "客户订单明细",
                "verbose_name_plural": "客户订单明细管理",
            },
        ),
        migrations.AlterField(
            model_name="artwork",
            name="confirmed",
            field=models.BooleanField(
                default=False, help_text="设计部是否已确认", verbose_name="已确认"
            ),
        ),
        migrations.AlterField(
            model_name="artwork",
            name="confirmed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_confirmed",
                to=settings.AUTH_USER_MODEL,
                verbose_name="确认人",
            ),
        ),
        migrations.AlterField(
            model_name="deliveryitem",
            name="sales_order_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="delivery_items",
                to="workorder.salesorderitem",
                verbose_name="客户订单明细",
            ),
        ),
        migrations.AlterField(
            model_name="deliveryorder",
            name="sales_order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="delivery_orders",
                to="workorder.salesorder",
                verbose_name="客户订单",
            ),
        ),
        migrations.AlterField(
            model_name="die",
            name="confirmed",
            field=models.BooleanField(
                default=False, help_text="设计部是否已确认", verbose_name="已确认"
            ),
        ),
        migrations.AlterField(
            model_name="die",
            name="confirmed_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="确认时间"),
        ),
        migrations.AlterField(
            model_name="die",
            name="confirmed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_confirmed",
                to=settings.AUTH_USER_MODEL,
                verbose_name="确认人",
            ),
        ),
        migrations.AlterField(
            model_name="embossingplate",
            name="confirmed",
            field=models.BooleanField(
                default=False, help_text="设计部是否已确认", verbose_name="已确认"
            ),
        ),
        migrations.AlterField(
            model_name="embossingplate",
            name="confirmed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_confirmed",
                to=settings.AUTH_USER_MODEL,
                verbose_name="确认人",
            ),
        ),
        migrations.AlterField(
            model_name="foilingplate",
            name="confirmed",
            field=models.BooleanField(
                default=False, help_text="设计部是否已确认", verbose_name="已确认"
            ),
        ),
        migrations.AlterField(
            model_name="foilingplate",
            name="confirmed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_confirmed",
                to=settings.AUTH_USER_MODEL,
                verbose_name="确认人",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="sales_order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invoices",
                to="workorder.salesorder",
                verbose_name="客户订单",
            ),
        ),
        migrations.AlterField(
            model_name="material",
            name="code",
            field=models.CharField(
                blank=True, max_length=50, unique=True, verbose_name="物料编码"
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="sales_order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payments",
                to="workorder.salesorder",
                verbose_name="客户订单",
            ),
        ),
        migrations.AlterField(
            model_name="paymentplan",
            name="sales_order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payment_plans",
                to="workorder.salesorder",
                verbose_name="客户订单",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="code",
            field=models.CharField(
                blank=True, max_length=50, unique=True, verbose_name="产品编码"
            ),
        ),
        migrations.AlterField(
            model_name="productgroup",
            name="code",
            field=models.CharField(
                blank=True, max_length=50, unique=True, verbose_name="产品组编码"
            ),
        ),
        migrations.AlterField(
            model_name="salesorder",
            name="order_number",
            field=models.CharField(
                max_length=50, unique=True, verbose_name="客户订单号"
            ),
        ),
        migrations.AlterField(
            model_name="salesorderitem",
            name="sales_order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="workorder.salesorder",
                verbose_name="客户订单",
            ),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="code",
            field=models.CharField(
                blank=True, max_length=50, unique=True, verbose_name="供应商编码"
            ),
        ),
        migrations.AlterField(
            model_name="workorder",
            name="customer",
            field=models.ForeignKey(
                help_text="客户订单客户快照，创建施工单时自动复制，请勿手动修改",
                on_delete=django.db.models.deletion.PROTECT,
                to="workorder.customer",
                verbose_name="客户",
            ),
        ),
        migrations.AlterField(
            model_name="workorder",
            name="delivery_date",
            field=models.DateField(
                help_text="客户订单交期快照，创建施工单时自动复制，请勿手动修改",
                verbose_name="交货日期",
            ),
        ),
        migrations.AlterField(
            model_name="workorder",
            name="order_date",
            field=models.DateField(
                default=datetime.date.today,
                help_text="客户订单日期快照，创建施工单时自动复制，请勿手动修改",
                verbose_name="下单日期",
            ),
        ),
        migrations.AlterField(
            model_name="workorder",
            name="total_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="客户订单金额快照，创建施工单时自动复制，请勿手动修改",
                max_digits=12,
                verbose_name="总金额",
            ),
        ),
    ]
