# Generated by Django 4.2.11 on 2026-05-29 09:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("workorder", "0060_alter_salesorder_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="invoice",
            options={
                "ordering": ["-created_at"],
                "permissions": [
                    ("approve_invoice", "可以审核发票"),
                    ("submit_invoice", "可以提交发票审核"),
                    ("change_approved_invoice", "可以编辑已审核的发票"),
                ],
                "verbose_name": "发票",
                "verbose_name_plural": "发票管理",
            },
        ),
        migrations.AlterModelOptions(
            name="purchaseorder",
            options={
                "ordering": ["-created_at"],
                "permissions": [
                    ("approve_purchaseorder", "可以审核采购单"),
                    ("submit_purchaseorder", "可以提交采购单审核"),
                    ("change_approved_purchaseorder", "可以编辑已审核的采购单"),
                ],
                "verbose_name": "采购单",
                "verbose_name_plural": "采购单管理",
            },
        ),
        migrations.AlterModelOptions(
            name="salesorder",
            options={
                "ordering": ["-created_at"],
                "permissions": [
                    ("approve_salesorder", "可以审核客户订单"),
                    ("submit_salesorder", "可以提交客户订单审核"),
                    ("change_approved_salesorder", "可以编辑已审核的客户订单"),
                ],
                "verbose_name": "客户订单",
                "verbose_name_plural": "客户订单管理",
            },
        ),
        migrations.AddField(
            model_name="invoice",
            name="approval_comment",
            field=models.TextField(blank=True, verbose_name="审核意见"),
        ),
        migrations.AddField(
            model_name="invoice",
            name="approval_status",
            field=models.CharField(
                choices=[
                    ("draft", "草稿"),
                    ("submitted", "待审核"),
                    ("approved", "已审核"),
                    ("rejected", "已拒绝"),
                ],
                default="draft",
                max_length=20,
                verbose_name="审核状态",
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="approval_comment",
            field=models.TextField(blank=True, verbose_name="审核意见"),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="approval_status",
            field=models.CharField(
                choices=[
                    ("draft", "草稿"),
                    ("submitted", "待审核"),
                    ("approved", "已审核"),
                    ("rejected", "已拒绝"),
                ],
                default="draft",
                max_length=20,
                verbose_name="审核状态",
            ),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="approval_status",
            field=models.CharField(
                choices=[
                    ("draft", "草稿"),
                    ("submitted", "待审核"),
                    ("approved", "已审核"),
                    ("rejected", "已拒绝"),
                ],
                default="draft",
                max_length=20,
                verbose_name="审核状态",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_%(class)s_set",
                to=settings.AUTH_USER_MODEL,
                verbose_name="审核人",
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_%(class)s_set",
                to=settings.AUTH_USER_MODEL,
                verbose_name="审核人",
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "待处理"),
                    ("ordered", "已下单"),
                    ("received", "已收货"),
                    ("cancelled", "已取消"),
                ],
                default="pending",
                max_length=20,
                verbose_name="状态",
            ),
        ),
        migrations.AlterField(
            model_name="salesorder",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_%(class)s_set",
                to=settings.AUTH_USER_MODEL,
                verbose_name="审核人",
            ),
        ),
        migrations.AlterField(
            model_name="salesorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "待处理"),
                    ("in_production", "生产中"),
                    ("completed", "已完成"),
                    ("cancelled", "已取消"),
                ],
                default="pending",
                max_length=20,
                verbose_name="订单状态",
            ),
        ),
        migrations.AlterField(
            model_name="workorder",
            name="approval_comment",
            field=models.TextField(blank=True, verbose_name="审核意见"),
        ),
        migrations.AlterField(
            model_name="workorder",
            name="approval_status",
            field=models.CharField(
                choices=[
                    ("draft", "草稿"),
                    ("submitted", "待审核"),
                    ("approved", "已审核"),
                    ("rejected", "已拒绝"),
                ],
                default="draft",
                max_length=20,
                verbose_name="审核状态",
            ),
        ),
        migrations.AlterField(
            model_name="workorder",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_%(class)s_set",
                to=settings.AUTH_USER_MODEL,
                verbose_name="审核人",
            ),
        ),
        migrations.AlterField(
            model_name="workorderapprovallog",
            name="approval_status",
            field=models.CharField(
                choices=[
                    ("draft", "草稿"),
                    ("submitted", "待审核"),
                    ("approved", "已审核"),
                    ("rejected", "已拒绝"),
                ],
                max_length=20,
                verbose_name="审核状态",
            ),
        ),
    ]
