# Generated by Django 4.2.11 on 2026-05-29 09:22

from django.db import migrations


def migrate_approval_status(apps, schema_editor):
    SalesOrder = apps.get_model("workorder", "SalesOrder")
    PurchaseOrder = apps.get_model("workorder", "PurchaseOrder")
    Invoice = apps.get_model("workorder", "Invoice")

    # SalesOrder
    for so in SalesOrder.objects.all():
        if so.status == "draft":
            so.approval_status = "draft"
            so.status = "pending"
        elif so.status == "submitted":
            so.approval_status = "submitted"
            so.status = "pending"
        elif so.status == "approved":
            so.approval_status = "approved"
            so.status = "pending"
        elif so.status == "rejected":
            so.approval_status = "rejected"
            so.status = "pending"
        elif so.status in ["in_production", "completed", "cancelled"]:
            so.approval_status = "approved"
        so.save(update_fields=["approval_status", "status"])

    # PurchaseOrder
    for po in PurchaseOrder.objects.all():
        if po.status == "draft":
            po.approval_status = "draft"
            po.status = "pending"
        elif po.status == "submitted":
            po.approval_status = "submitted"
            po.status = "pending"
        elif po.status == "approved":
            po.approval_status = "approved"
            po.status = "pending"
        elif po.status in ["ordered", "received", "cancelled"]:
            po.approval_status = "approved"
        po.save(update_fields=["approval_status", "status"])

    # Invoice
    for inv in Invoice.objects.all():
        if inv.status == "draft":
            inv.approval_status = "draft"
        elif inv.status in ["issued", "sent"]:
            inv.approval_status = "submitted"
        elif inv.status == "received":
            inv.approval_status = "approved"
        elif inv.status in ["cancelled", "refunded"]:
            inv.approval_status = "rejected"
        else:
            inv.approval_status = "draft"
        inv.save(update_fields=["approval_status"])

def reverse_migrate(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        (
            "workorder",
            "0061_alter_invoice_options_alter_purchaseorder_options_and_more",
        ),
    ]

    operations = [
        migrations.RunPython(migrate_approval_status, reverse_migrate)
    ]
