# Generated by Django 4.2.8 on 2026-01-06 03:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workorder', '0062_add_foiling_embossing_plate_to_task'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artwork',
            options={'ordering': ['-base_code', '-version'], 'verbose_name': '图稿', 'verbose_name_plural': '图稿管理'},
        ),
        migrations.AlterField(
            model_name='artwork',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='确认时间'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_artworks', to=settings.AUTH_USER_MODEL, verbose_name='确认人'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='dies',
            field=models.ManyToManyField(blank=True, help_text='该图稿关联的刀模', to='workorder.die', verbose_name='关联刀模'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='embossing_plates',
            field=models.ManyToManyField(blank=True, help_text='该图稿关联的压凸版', to='workorder.embossingplate', verbose_name='关联压凸版'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='foiling_plates',
            field=models.ManyToManyField(blank=True, help_text='该图稿关联的烫金版', to='workorder.foilingplate', verbose_name='关联烫金版'),
        ),
        migrations.AlterField(
            model_name='workordertask',
            name='task_type',
            field=models.CharField(choices=[('plate_making', '制版任务'), ('cutting', '开料任务'), ('printing', '印刷任务'), ('foiling', '烫金任务'), ('embossing', '压凸任务'), ('die_cutting', '模切任务'), ('packaging', '包装任务'), ('general', '通用任务')], default='general', help_text='任务类型，用于区分不同的任务生成规则', max_length=20, verbose_name='任务类型'),
        ),
        migrations.CreateModel(
            name='TaskLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(choices=[('update_quantity', '更新数量'), ('complete', '强制完成'), ('status_change', '状态变更')], max_length=20, verbose_name='日志类型')),
                ('content', models.TextField(help_text='操作内容描述', verbose_name='内容')),
                ('quantity_before', models.IntegerField(blank=True, null=True, verbose_name='更新前数量')),
                ('quantity_after', models.IntegerField(blank=True, null=True, verbose_name='更新后数量')),
                ('status_before', models.CharField(blank=True, max_length=20, null=True, verbose_name='更新前状态')),
                ('status_after', models.CharField(blank=True, max_length=20, null=True, verbose_name='更新后状态')),
                ('completion_reason', models.TextField(blank=True, help_text='强制完成时的理由说明', verbose_name='完成理由')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作员')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='workorder.workordertask', verbose_name='任务')),
            ],
            options={
                'verbose_name': '任务操作日志',
                'verbose_name_plural': '任务操作日志',
                'ordering': ['-created_at'],
            },
        ),
    ]
