# Generated by Django 4.2.11 on 2026-05-29 09:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("workorder", "0062_migrate_approval_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stockin",
            name="approved_at",
        ),
        migrations.RemoveField(
            model_name="stockin",
            name="approved_by",
        ),
        migrations.RemoveField(
            model_name="stockout",
            name="approved_at",
        ),
        migrations.RemoveField(
            model_name="stockout",
            name="approved_by",
        ),
        migrations.AddField(
            model_name="stockin",
            name="confirmed_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="确认时间"),
        ),
        migrations.AddField(
            model_name="stockin",
            name="confirmed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="confirmed_stock_ins",
                to=settings.AUTH_USER_MODEL,
                verbose_name="确认人",
            ),
        ),
        migrations.AddField(
            model_name="stockout",
            name="confirmed_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="确认时间"),
        ),
        migrations.AddField(
            model_name="stockout",
            name="confirmed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="confirmed_stock_outs",
                to=settings.AUTH_USER_MODEL,
                verbose_name="确认人",
            ),
        ),
    ]
