# Generated by Django 4.2.8 on 2026-01-06 04:35

from django.db import migrations, models


def set_parallel_processes(apps, schema_editor):
    """为预设工序设置 is_parallel 字段"""
    Process = apps.get_model('workorder', 'Process')
    # 制版(CTP)和模切(DIE)可以并行执行
    Process.objects.filter(code__in=['CTP', 'DIE']).update(is_parallel=True)


def reverse_parallel_processes(apps, schema_editor):
    """回滚操作：清空 is_parallel 字段"""
    Process = apps.get_model('workorder', 'Process')
    Process.objects.all().update(is_parallel=False)


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0063_alter_artwork_options_alter_artwork_confirmed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='is_parallel',
            field=models.BooleanField(default=False, help_text='该工序是否可以与其他工序并行执行（如制版、模切等）', verbose_name='可并行执行'),
        ),
        migrations.RunPython(set_parallel_processes, reverse_parallel_processes),
    ]
