# Generated by Django 4.2.11 on 2026-05-30 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workorder", "0063_remove_stockin_approved_at_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="workorder",
            options={
                "ordering": ["-created_at"],
                "permissions": [
                    ("approve_workorder", "可以审核施工单"),
                    ("submit_workorder", "可以提交施工单审核"),
                    ("change_approved_workorder", "可以编辑已审核的施工单"),
                ],
                "verbose_name": "施工单",
                "verbose_name_plural": "施工单管理",
            },
        ),
    ]
