# Generated by Django 4.2.8 on 2026-01-06 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0064_add_is_parallel_to_process'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklog',
            name='quantity_increment',
            field=models.IntegerField(blank=True, help_text='本次操作的数量增量', null=True, verbose_name='数量增量'),
        ),
    ]
