# Generated by Codex on 2026-06-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workorder", "0064_alter_workorder_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchaseorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "待下单"),
                    ("ordered", "已下单"),
                    ("received", "已收货"),
                    ("cancelled", "已取消"),
                ],
                default="pending",
                max_length=20,
                verbose_name="状态",
            ),
        ),
    ]
