# Generated by Django 4.2.8 on 2026-01-06 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0065_add_quantity_increment_to_tasklog'),
        ('workorder', '0023_reset_departments'),  # 确保在0023之后执行
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='上级部门，用于建立部门层级关系（如生产部下有多个车间）', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='workorder.department', verbose_name='上级部门'),
        ),
        migrations.AlterField(
            model_name='process',
            name='artwork_required',
            field=models.BooleanField(default=True, help_text='如果为True，选择该工序时必须选择图稿；如果为False，图稿可选（但需要手动创建设计任务，设计不属于施工单工序）', verbose_name='图稿必选'),
        ),
        migrations.AlterField(
            model_name='process',
            name='die_required',
            field=models.BooleanField(default=True, help_text='如果为True，选择该工序时必须选择刀模；如果为False，刀模可选（但需要手动创建设计任务，设计不属于施工单工序）', verbose_name='刀模必选'),
        ),
        migrations.AlterField(
            model_name='process',
            name='embossing_plate_required',
            field=models.BooleanField(default=True, help_text='如果为True，选择该工序时必须选择压凸版；如果为False，压凸版可选（但需要手动创建设计任务，设计不属于施工单工序）', verbose_name='压凸版必选'),
        ),
        migrations.AlterField(
            model_name='process',
            name='foiling_plate_required',
            field=models.BooleanField(default=True, help_text='如果为True，选择该工序时必须选择烫金版；如果为False，烫金版可选（但需要手动创建设计任务，设计不属于施工单工序）', verbose_name='烫金版必选'),
        ),
    ]
