# Generated by Django 4.2.11 on 2026-06-01 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("workorder", "0065_alter_purchaseorder_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="deliveryorder",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "送货单",
                "verbose_name_plural": "送货单管理",
            },
        ),
        migrations.AlterField(
            model_name="deliveryitem",
            name="delivery_order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="workorder.deliveryorder",
                verbose_name="送货单",
            ),
        ),
        migrations.AlterField(
            model_name="deliveryorder",
            name="order_number",
            field=models.CharField(
                editable=False, max_length=50, unique=True, verbose_name="送货单号"
            ),
        ),
        migrations.AlterField(
            model_name="salesorderitem",
            name="delivered_quantity",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="已通过送货单发出的数量",
                max_digits=10,
                verbose_name="已发货数量",
            ),
        ),
        migrations.AlterField(
            model_name="stockout",
            name="delivery_order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stock_outs",
                to="workorder.deliveryorder",
                verbose_name="送货单",
            ),
        ),
    ]
