# Generated by Django 4.2.8 on 2026-01-06

from django.db import migrations


def update_department_hierarchy(apps, schema_editor):
    """更新部门结构，建立层级关系
    
    部门结构：
    - 管理部门：业务部、财务部、设计部、采购部、运输部（保持不变）
    - 生产部（新建父部门）
      - 裁切车间（原裁切部）
      - 印刷车间（原印刷部）
      - 外协车间（原外协部）
      - 模切车间（原模切部）
      - 包装车间（原包装部）
    """
    Department = apps.get_model('workorder', 'Department')
    
    # 1. 创建生产部（如果不存在）
    production_dept, created = Department.objects.get_or_create(
        code='production',
        defaults={
            'name': '生产部',
            'sort_order': 5,
            'is_active': True,
            'parent': None
        }
    )
    if created:
        print(f"✓ 创建生产部: {production_dept.name}")
    else:
        # 如果已存在，确保parent为None
        if production_dept.parent:
            production_dept.parent = None
            production_dept.save()
    
    # 2. 更新生产车间，设置parent为生产部，并重命名
    workshop_mapping = {
        'cutting': {'name': '裁切车间', 'old_name': '裁切部'},
        'printing': {'name': '印刷车间', 'old_name': '印刷部'},
        'outsourcing': {'name': '外协车间', 'old_name': '外协部'},
        'die_cutting': {'name': '模切车间', 'old_name': '模切部'},
        'packaging': {'name': '包装车间', 'old_name': '包装部'},
    }
    
    for code, data in workshop_mapping.items():
        try:
            dept = Department.objects.get(code=code)
            # 更新名称和parent
            dept.name = data['name']
            dept.parent = production_dept
            dept.save()
            print(f"✓ 更新部门: {data['old_name']} -> {data['name']} (父部门: 生产部)")
        except Department.DoesNotExist:
            # 如果部门不存在，创建它
            Department.objects.create(
                name=data['name'],
                code=code,
                sort_order=workshop_mapping[code].get('sort_order', 0),
                is_active=True,
                parent=production_dept
            )
            print(f"✓ 创建部门: {data['name']} (父部门: 生产部)")


def reverse_update_department_hierarchy(apps, schema_editor):
    """回滚操作：恢复为扁平结构"""
    Department = apps.get_model('workorder', 'Department')
    
    # 恢复车间名称为"部"
    workshop_mapping = {
        'cutting': '裁切部',
        'printing': '印刷部',
        'outsourcing': '外协部',
        'die_cutting': '模切部',
        'packaging': '包装部',
    }
    
    for code, old_name in workshop_mapping.items():
        try:
            dept = Department.objects.get(code=code)
            dept.name = old_name
            dept.parent = None
            dept.save()
        except Department.DoesNotExist:
            pass
    
    # 删除生产部
    try:
        production_dept = Department.objects.get(code='production')
        production_dept.delete()
    except Department.DoesNotExist:
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0066_add_department_parent'),
    ]

    operations = [
        migrations.RunPython(update_department_hierarchy, reverse_update_department_hierarchy),
    ]
