# Generated by Django 4.2.8 on 2026-01-06 09:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workorder', '0068_change_userprofile_department_to_manytomany'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrderApprovalLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval_status', models.CharField(choices=[('pending', '待审核'), ('approved', '已通过'), ('rejected', '已拒绝')], max_length=20, verbose_name='审核状态')),
                ('approved_at', models.DateTimeField(auto_now_add=True, verbose_name='审核时间')),
                ('approval_comment', models.TextField(blank=True, help_text='审核意见或说明', verbose_name='审核意见')),
                ('rejection_reason', models.TextField(blank=True, help_text='审核拒绝时的拒绝原因', verbose_name='拒绝原因')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_logs', to=settings.AUTH_USER_MODEL, verbose_name='审核人')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_logs', to='workorder.workorder', verbose_name='施工单')),
            ],
            options={
                'verbose_name': '施工单审核历史',
                'verbose_name_plural': '施工单审核历史管理',
                'ordering': ['-approved_at', '-created_at'],
            },
        ),
    ]
