# Generated by Django 4.2.8 on 2026-01-06 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0069_add_approval_log'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workorder',
            options={'ordering': ['-created_at'], 'permissions': [('change_approved_workorder', '可以编辑已审核的施工单')], 'verbose_name': '施工单', 'verbose_name_plural': '施工单管理'},
        ),
    ]
