"""
角色权限矩阵 - 业务角色与权限的对应关系

本模块是角色权限矩阵的唯一来源，init_groups 和测试都从这里读取。
"""

ROLE_PERMISSIONS = {
    "sales": {
        "WorkOrder": ["add", "view"],
        "SalesOrder": ["add", "view", "change"],
        "SalesOrderItem": ["add", "view", "change"],
        "Customer": ["add", "view", "change"],
        "Process": ["view"],
        "Department": ["view"],
        "Product": ["add", "view", "change"],
        "ProductGroup": ["view"],
        "ProductGroupItem": ["view"],
        "ProductMaterial": ["view"],
        "Material": ["add", "view", "change"],
        "Supplier": ["view"],
        "MaterialSupplier": ["view"],
        "Artwork": ["add", "view", "change"],
        "ArtworkProduct": ["view"],
        "Die": ["view"],
        "DieProduct": ["view"],
        "FoilingPlate": ["add", "view", "change"],
        "FoilingPlateProduct": ["view"],
        "EmbossingPlate": ["add", "view", "change"],
        "EmbossingPlateProduct": ["view"],
        "DeliveryOrder": ["add", "view", "change"],
        "DeliveryItem": ["view"],
        "Invoice": ["view"],
        "Payment": ["view"],
        "PaymentPlan": ["view"],
        "Statement": ["view"],
    },
    "design": {
        "WorkOrder": ["view"],
        "WorkOrderTask": ["view", "change"],
        "Process": ["view"],
        "Department": ["view"],
        "Artwork": ["add", "view", "change"],
        "ArtworkProduct": ["view"],
        "Die": ["add", "view", "change"],
        "DieProduct": ["view"],
        "FoilingPlate": ["add", "view", "change"],
        "FoilingPlateProduct": ["view"],
        "EmbossingPlate": ["add", "view", "change"],
        "EmbossingPlateProduct": ["view"],
    },
    "supervisor": {
        "WorkOrder": ["view", "change"],
        "WorkOrderProcess": ["view", "change"],
        "WorkOrderTask": ["view", "change"],
        "WorkOrderMaterial": ["view", "change"],
        "WorkOrderProduct": ["view", "change"],
        "ProcessLog": ["view"],
        "TaskLog": ["view"],
        "Process": ["view"],
        "Department": ["view"],
        "Product": ["view"],
        "Material": ["view"],
        "Supplier": ["view"],
        "PurchaseOrder": ["view", "change"],
        "PurchaseOrderItem": ["view", "change"],
        "PurchaseReceiveRecord": ["view", "change"],
        "ProductStock": ["view", "change"],
        "StockIn": ["view", "change"],
        "StockOut": ["view", "change"],
        "DeliveryOrder": ["view", "change"],
        "DeliveryItem": ["view", "change"],
        "QualityInspection": ["view", "change"],
        "SalesOrder": ["view"],
        "Invoice": ["view"],
        "Payment": ["view"],
        "PaymentPlan": ["view"],
        "Statement": ["view"],
        "ProductionCost": ["view"],
        "TaskAssignmentRule": ["view", "change"],
    },
    "manager": {
        "WorkOrder": ["view", "change"],
        "WorkOrderProcess": ["view", "change"],
        "WorkOrderTask": ["view", "change"],
        "WorkOrderMaterial": ["view", "change"],
        "WorkOrderProduct": ["view", "change"],
        "ProcessLog": ["view"],
        "TaskLog": ["view"],
        "Process": ["view"],
        "Department": ["view"],
        "Product": ["add", "view", "change"],
        "ProductGroup": ["add", "view", "change"],
        "ProductGroupItem": ["add", "view", "change"],
        "ProductMaterial": ["add", "view", "change"],
        "Artwork": ["add", "view", "change"],
        "Die": ["add", "view", "change"],
        "FoilingPlate": ["add", "view", "change"],
        "EmbossingPlate": ["add", "view", "change"],
        "Material": ["add", "view", "change"],
        "Supplier": ["add", "view", "change"],
        "PurchaseOrder": ["add", "view", "change"],
        "PurchaseOrderItem": ["add", "view", "change"],
        "PurchaseReceiveRecord": ["view", "change"],
        "ProductStock": ["view", "change"],
        "StockIn": ["view", "change"],
        "StockOut": ["view", "change"],
        "DeliveryOrder": ["add", "view", "change"],
        "DeliveryItem": ["view", "change"],
        "QualityInspection": ["view", "change"],
        "SalesOrder": ["view", "change"],
        "Invoice": ["view", "change"],
        "Payment": ["view", "change"],
        "PaymentPlan": ["view", "change"],
        "Statement": ["view", "change"],
        "ProductionCost": ["view", "change"],
        "CostCenter": ["view", "change"],
        "CostItem": ["view", "change"],
        "TaskAssignmentRule": ["view", "change"],
        "AuditLog": ["view"],
        "AuditLogExport": ["view"],
        "AuditLogSettings": ["view", "change"],
    },
    "operator": {
        "WorkOrder": ["view"],
        "WorkOrderTask": ["view", "change"],
        "Process": ["view"],
        "Department": ["view"],
        "Product": ["view"],
        "Material": ["view"],
        "ProductStock": ["view"],
        "StockIn": ["view"],
        "StockOut": ["view"],
    },
    "finance": {
        "SalesOrder": ["view"],
        "Customer": ["view"],
        "Supplier": ["add", "view", "change"],
        "Invoice": ["add", "view", "change"],
        "Payment": ["add", "view", "change"],
        "PaymentPlan": ["view", "change"],
        "Statement": ["add", "view", "change"],
        "ProductionCost": ["view", "change"],
        "CostCenter": ["view", "change"],
        "CostItem": ["view", "change"],
    },
    "procurement": {
        "Supplier": ["add", "view", "change"],
        "MaterialSupplier": ["add", "view", "change"],
        "Material": ["view"],
        "PurchaseOrder": ["add", "view", "change"],
        "PurchaseOrderItem": ["add", "view", "change"],
        "PurchaseReceiveRecord": ["view", "change"],
        "ProductStock": ["view"],
        "StockIn": ["view"],
    },
    "inventory": {
        "WorkOrder": ["view"],
        "SalesOrder": ["view"],
        "Product": ["view"],
        "Material": ["view"],
        "ProductStock": ["view", "change"],
        "StockIn": ["add", "view", "change"],
        "StockOut": ["add", "view", "change"],
        "DeliveryOrder": ["add", "view", "change"],
        "DeliveryItem": ["view", "change"],
        "PurchaseReceiveRecord": ["view", "change"],
    },
    "quality": {
        "WorkOrder": ["view"],
        "WorkOrderTask": ["view"],
        "Product": ["view"],
        "Material": ["view"],
        "QualityInspection": ["add", "view", "change"],
        "PurchaseReceiveRecord": ["view", "change"],
        "ProductStock": ["view"],
        "StockIn": ["view"],
    },
    "admin": {
        "Customer": ["view", "change"],
        "Supplier": ["view", "change"],
        "Department": ["add", "view", "change"],
        "Process": ["add", "view", "change"],
        "Artwork": ["add", "view", "change", "delete"],
        "Die": ["add", "view", "change", "delete"],
        "FoilingPlate": ["add", "view", "change", "delete"],
        "EmbossingPlate": ["add", "view", "change", "delete"],
        "Product": ["add", "view", "change", "delete"],
        "ProductMaterial": ["add", "view", "change", "delete"],
        "ProductGroup": ["add", "view", "change", "delete"],
        "ProductGroupItem": ["add", "view", "change", "delete"],
        "ProductImage": ["add", "view", "change", "delete"],
        "TaskAssignmentRule": ["add", "view", "change"],
        "SystemNotificationSettings": ["view", "change"],
        "NotificationTemplate": ["add", "view", "change", "delete"],
        "Notification": ["view", "change"],
        "AuditLog": ["view"],
        "AuditLogExport": ["view"],
        "AuditLogSettings": ["view", "change"],
    },
}

ROLE_CUSTOM_PERMISSIONS = {
    "manager": {
        "WorkOrder": ["change_approved_workorder", "delete_workorder", "submit_workorder"],
        "SalesOrder": ["change_approved_salesorder", "submit_salesorder"],
        "PurchaseOrder": ["change_approved_purchaseorder", "submit_purchaseorder"],
        "Invoice": ["change_approved_invoice", "submit_invoice"],
    },
    "supervisor": {
        "WorkOrder": ["approve_workorder", "submit_workorder"],
        "SalesOrder": ["approve_salesorder", "submit_salesorder"],
        "PurchaseOrder": ["approve_purchaseorder", "submit_purchaseorder"],
        "Invoice": ["approve_invoice", "submit_invoice"],
    },
    "finance": {
        "Invoice": ["approve_invoice", "change_approved_invoice", "submit_invoice"],
    },
    "procurement": {
        "PurchaseOrder": ["approve_purchaseorder", "change_approved_purchaseorder", "submit_purchaseorder"],
    },
    "sales": {
        "SalesOrder": ["submit_salesorder"],
    },
    "operator": {
        "WorkOrder": ["submit_workorder"],
    },
}

ROLE_ALIASES = {
    "业务员": "sales",
    "主管": "supervisor",
    "经理": "manager",
    "操作员": "operator",
    "财务": "finance",
    "采购": "procurement",
    "设计": "design",
    "设计/制版": "design",
    "仓储": "inventory",
    "质检": "quality",
    "系统管理员": "admin",
    "salespersons": "sales",
    "operators": "operator",
    "managers": "manager",
    "administrators": "admin",
}

# 废弃模型列表（已确认无实体引用，可安全清理）
STALE_PERMISSION_MODELS: set = set()
